CHANGELOG.md
The changelog didn't have a good description of the recent beta tag renames so
I added them for the 1.0 release
=> docs(changelog): improve changelog notes for 1.0.0

Jenkinsfile, src/components/beta/gux-tabs/gux-tabs.tsx
Avoid build loops by checking to see if the last commit was a release commit when building
I was able to validate that this does avoid build loops by using Jenkins' replay feature, but I'll also want to check that it builds correctly after we've merged some PRs for builds that shouldn't be skipped.
=> ci(jenkinsfile): avoid build loops

src/components/beta/gux-table/gux-table.tsx
added guards to resizeObserver calls if it is undefined
=> fix(gux-table): resizeObserver not present in spec tests

docs/src/component-listing/app.js
I noticed this when looking at the color PR, so here's a quick fix.
=> fix(doc-site): fix the sort order of components

Jenkinsfile, scripts/version-helper.js
Feature branch uploads were almost working, but the Jenkinsfile was missing logic to handle
overriding the upload version. This adds that and cleans up a bit of old code related to alpha
deploys that I found while working.
any existing `feature/...` branches will need to be rebased/merged with this to get their deploys working.
=> ci(jenkins): fix uploading of feature branches

docs/src/component-viewer/app.js, docs/src/styles/component-viewer.less
This hides the attribute/event panel in the demo docs with a gux-disclosure-button. It's not the
most discoverable approach, but it's a good quick fix to make the embedded docs look a lot less
cluttered, IMO.
COMUI-270
=> docs(attribute-panel): hide attribute panel with gux-disclosure-button

src/components/beta/gux-tabs/gux-tab/gux-tab.less
=> fix(gux-tab): fix margin of gux-tab dropdown

src/components/stable/gux-icon/example.html, src/components/stable/gux-icon/gux-icon.less
in some cases, icons svgs without a square aspect ratio would overflow the gux-icon component or not
be centered within it. This corrects those issues.
COMUI-333
=> fix(icons): improve handling for non-square icon svgs

src/components/stable/gux-pagination/gux-pagination-items-per-page/gux-pagination-items-per-page.less
The pagination component is almost always placed at the bottom of the page, but the item count
selection uses a dropdown, which is awkward in that position. This is a bit of a kludgy fix to make
the component drop-up instead, until we land COMUI-242, which should give us a better general
mechanism for this behavior.
=> fix(pagination): drop-up instead of drop-down

src/components/stable/gux-dropdown/gux-dropdown.tsx
Fix dropdown behavior, to show placeholder if focus is lost while an invalid value was entered.
fix https://inindca.atlassian.net/browse/COMUI-339
=> fix(gux-dropdown): revert to no value if invalid value entered when focus is lost

src/components/stable/gux-disclosure-button/gux-disclosure-button.tsx, src/components/stable/gux-disclosure-button/tests/gux-disclosure-button.e2e.ts
Update icon when is-open attribute changes
The updateIcon() function was called when the button was clicked, but not when `is-open` attribute was updated
COMUI-336
=> fix(gux-disclosure-button): update icon when is-open attribute changes

package.json, stencil.config.ts
When building in Jenkins, i18n files were not being correctly added to the 'dist' folder. This fixes
that issue.
COMUI-341
This one was a bear to sort out. There's no obvious reason it wouldn't work, but I eventually realized that if I ran multiple builds locally, every other build would be missing the files from the rollup copy plugin. Since the Jenkins job builds the components for running tests and for deployment, that seemed like a likely culprit, so I tried removing the output directory before building, and that solved the problem.
=> fix(i18n): fix i18n build in Jenkins

docs/src/utils/generateIconsPage.js, docs/webpack.config.js, src/components/stable/gux-icon/example.html, src/components/stable/gux-icon/gux-icon.less
Dynamically generate a list of all `.svg` files in the `/src/components/stable/gux-icon/icons` and places them inside HTML elements on the `gux-icon` docs page during the webpack build.
=> docs(gux-icon): added a list of all icons to the docs page

src/components/beta/gux-tabs/gux-tabs.tsx
Issue: the scrollbar on gux-tabs would continue to show when tabs were removed
Example Before This Fix:
Example After This Fix:
MutationObserver is supported on all major browsers (including IE11)
=> fix(gux-tabs): re-check scrollbar hide/show when dom changes

src/components/beta/gux-table/gux-row-select/gux-row-select.tsx
https://inindca.atlassian.net/browse/COMUI-435
The component was using gux-checkbox but with the move to 2.0 it needed to get -legacy added to it so it would still work.
=> fix(gux-row-select): update gux-row-select to use gux-checkbox-legacy

src/components/beta/gux-tag/gux-tag.types.ts, src/components/beta/gux-tag/readme.md
Fixed a typo in the `GuxTagColor` type
`alert-ellow-green` is updated to `alert-yellow-green`
=> fix(gux-tag color type): fixed a typo in the tag color type

src/components/stable/gux-disclosure-button/gux-disclosure-button.less
Style conflicts are resolved for the user defined buttons inside the `gux-disclosure-button` component
=> fix(gux-disclosure-button): gux class name added for the css selector to avoid conflicts

src/components/stable/gux-advanced-dropdown/dropdown-option/gux-dropdown-option.less, src/components/stable/gux-advanced-dropdown/dropdown-option/gux-dropdown-option.tsx, src/components/stable/gux-advanced-dropdown/example.html, src/components/stable/gux-advanced-dropdown/gux-advanced-dropdown.less, src/components/stable/gux-advanced-dropdown/gux-advanced-dropdown.tsx
Text overflows and overlapping issues are now fixed.
After Fix:
Before Fix:
Also did a testing with screenreader to check if it is reading only once, and it passed. 
Since the `title` attribute is added to elements which is not having `tabIndex=0` or focusable, the screenreader is working just fine.
=> fix(gux-advanced-dropdown): text overflow issues are fixed

src/components/stable/gux-form-field/components/gux-input-range/gux-input-range.tsx
Addresses bug for ticket COMUI-541 
Somehow a change in [COMUI-437: Remove gux-checkbox-legacy dependency from gux-row-select](https://inindca.atlassian.net/browse/COMUI-437) caused an issue in the gux-input-range component in the deployed webcomponents docs and Spark site. I can't find why that PR would have caused an issue with the gux-input-range component as it is not immediately apparent. To complicate things further, the bug cannot be reproduced locally, only when deployed in a feature branch.
The gux-input-range component was trying to reference the input before it was defined and as a result the component was not functional
There are two ways to fix this bug. One is to revert the changes in COMUI-437 (the revert is in the branch feature/COMUI-541-revert-bug) and then try to …
=> fix(gux-input-range): fixed bug with gux-input-range race condition

docs/src/component-viewer/components/checkbox-attribute.js, scripts/generate-component-data.js
Previously boolean attributes were displayed as dropdowns. This is now fixed and it appears as checkboxes properly.
`boolean` attribute with checkboxes
=> fix(attributes-panel): boolean attributes will now appear as checkboxes properly

src/components/stable/gux-tooltip/gux-tooltip.tsx
My original idea was to use a MutationObserver to monitor if the forElement became disabled and act accordingly. This had a lot of issues, and I realized I could make a much much simpler solution just by flipping a boolean back and forth.
This shouldn't cause any issues anywhere else, but let me know.
=> fix(tooltip): fixed Tooltip doesn't disappear when button is disabled

src/components/stable/gux-form-field/components/gux-input-number/gux-input-number.less
=> fix(gux-input-number): number input is now aligned to the right

src/components/stable/gux-form-field/components/gux-input-color/i18n/cs.json, src/components/stable/gux-form-field/components/gux-input-color/i18n/da.json, src/components/stable/gux-form-field/components/gux-input-color/i18n/de.json, src/components/stable/gux-form-field/components/gux-input-color/i18n/es-es.json, src/components/stable/gux-form-field/components/gux-input-color/i18n/es.json, src/components/stable/gux-form-field/components/gux-input-color/i18n/fi.json, src/components/stable/gux-form-field/components/gux-input-color/i18n/fr-ca.json, src/components/stable/gux-form-field/components/gux-input-color/i18n/fr.json, src/components/stable/gux-form-field/components/gux-input-color/i18n/it.json, src/components/stable/gux-form-field/components/gux-input-color/i18n/ja.json, src/components/stable/gux-form-field/components/gux-input-color/i18n/ko.json, src/components/stable/gux-form-field/components/gux-input-color/i18n/nl.json, src/components/stable/gux-form-field/components/gux-input-color/i18n/no.json, src/components/stable/gux-form-field/components/gux-input-color/i18n/pl.json, src/components/stable/gux-form-field/components/gux-input-color/i18n/pt-br.json, src/components/stable/gux-form-field/components/gux-input-color/i18n/ru.json, src/components/stable/gux-form-field/components/gux-input-color/i18n/sv.json, src/components/stable/gux-form-field/components/gux-input-color/i18n/th.json, src/components/stable/gux-form-field/components/gux-input-color/i18n/tr.json, src/components/stable/gux-form-field/components/gux-input-color/i18n/zh-cn.json, src/components/stable/gux-form-field/components/gux-input-color/i18n/zh-tw.json
Translation Process Automation generated string (DO NOT EDIT): [src/components/stable/gux-form-field/components/gux-input-color/i18n/cs.json,src/components/stable/gux-form-field/components/gux-input-color/i18n/da.json,src/components/stable/gux-form-field/components/gux-input-color/i18n/de.json,src/components/stable/gux-form-field/components/gux-input-color/i18n/es-es.json,src/components/stable/gux-form-field/components/gux-input-color/i18n/es.json,src/components/stable/gux-form-field/components/gux-input-color/i18n/fi.json,src/components/stable/gux-form-field/components/gux-input-color/i18n/fr-ca.json,src/components/stable/gux-form-field/components/gux-input-color/i18n/fr.json,src/components/stable/gux-form-field/components/gux-input-color/i18n/it.json,src/components/stable/gux-form-field/ …
=> chore(translations): translation updates

src/components/stable/gux-form-field/components/gux-input-number/example.html, src/components/stable/gux-form-field/components/gux-input-number/gux-input-number.less, src/components/stable/gux-form-field/components/gux-input-select/example.html, src/components/stable/gux-form-field/components/gux-input-text-like/example.html, src/components/stable/gux-form-field/example.html, src/components/stable/gux-form-field/gux-form-field.less
Fixed `gux-form-field` input overflow issue and fixed `gux-input-number` alignment issue that would show when width of container is less than ~130px
COMUI-585
=> fix(gux-form-field): fixed gux-form-field overflow issue

src/components/stable/gux-button/gux-button.less
COMUI-566 -- Fixed alignment of icons and text in gux-button. Does not break styling of buttons with multiple spans or text overflow ellipsis.
Before:
After:
=> fix(gux-button): align icon and text

src/components/stable/gux-button/gux-button.tsx, src/components/stable/gux-button/readme.md, src/components/stable/gux-button/tests/gux-button.e2e.ts
Adds a `focusElement` API on the `gux-button` component.
=> feat(button): add method for programatically focusing

package-lock.json, package.json, src/components/beta/gux-dismiss-button/gux-dismiss-button.tsx, src/components/stable/gux-button/gux-button.tsx, src/components/stable/gux-modal/example.html, src/components/stable/gux-modal/gux-modal.tsx, src/components/stable/gux-modal/readme.md, src/components/stable/gux-modal/tests/gux-modal.e2e.ts, src/components/stable/gux-modal/tests/gux-modal.spec.ts
Modifies `gux-modal` [to follow accessibility guidelines](https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal) a little better.  
* Keyboard focus moves to the modal when it opens
* Keyboard focus is trapped in the modal - cannot focus an element outside the modal via keyboard navigation.
* Keyboard focus returns to the originally focused element when the modal closes
* Modal can be closed with the escape key
There's also an option for customizing the initial focus element if the first focusable element in the modal isn't the desired behavior.  (e.g. to select the least destructive action).
---
Two notes: 
* In this version the dismiss button isn't tabbable - (I think that's due to [how focus-trap detects tabbable elements](https://github.com/focus-trap/tabbable#more-details)).  I …
=> Better aria behavior for modal - trap focus and dismiss via escape

src/components/beta/gux-tooltip-title/gux-tooltip-title.less, src/components/stable/gux-tooltip/gux-tooltip.tsx, src/components/stable/gux-tooltip/tests/__snapshots__/gux-tooltip.spec.ts.snap, src/components/stable/gux-tooltip/tests/gux-tooltip.e2e.ts, src/style/style.less
Gux-tooltip was enforcing `cursor: pointer` styling on the linked element. Per discussion in standup, removed this styling to allow linked element to define its own cursor styles (ie `cursor: help` for a help tooltip).
The removed style was added during a component API change last year. Later this style was made `!important` related to the gux-tabs-beta. Did not notice any negative consequences of removing the style on the documentation for gux-tooltip or gux-tabs-beta. Hopefully, Daragh or Katie can remember what its original use was and verify no regression.
COMUI-653
=> fix(gux-tooltip): remove cursor styling form linked element

src/components/stable/gux-icon/example.html, src/components/stable/gux-icon/gux-icon.service.tsx, src/components/stable/gux-icon/gux-icon.tsx
Now only one network request is fired even if the screen-reader texts are different.
=> fix(gux-icon): svg icon cache logic has been improved and reduced network calls

src/components/beta/gux-dropdown-v2/tests/__snapshots__/gux-dropdown-v2.spec.ts.snap
Two PRs that affected the `gux-dropdown-v2` component merged within a short time period, and GitHub did not show a failing build until after the second PR was already merged to master.
=> test(gux-dropdown-v2): fix failing snapshot test

Jenkinsfile
v2 should still be the deployed  branch for now
COMUI-711
(cherry picked from commit 4631432bf4096c96659eefe3ad889a3258a90807)
=> fix(docs): v2 should still be the deployed  branch for now

src/components/beta/gux-tabs-beta/gux-tab-list-beta/gux-tab-list-beta.tsx
COMUI-723
backport to v2
https://inindca.atlassian.net/browse/COMUI-723
I was unable to recreate the console errors that were reported in the ticket on the docs site or in the Ember playground, but this fix should solve the issue.
=> fix(gux-tabs-beta): fix gux-tab-beta console errors

src/components/stable/gux-icon/icon-name-map.ts
The `trade` icon was being mapped to use the `transfer` icon. The `trade` icon should be using its own icon.
=> fix(gux-icon): remap trade icon to use correct icon

docs/migrations/v3/readme.md
If `esModuleInterop` is already enabled, `allowSyntheticDefaultImports` does not need to be enabled.
=> docs: add clarification about allowSyntheticDefaultImports vs. esModuleInterop

src/components/stable/gux-disclosure-button/readme.md, src/components/stable/gux-tabs/gux-tab-list/gux-tab-list.less, src/components/stable/gux-tabs/gux-tab-list/gux-tab-list.tsx, src/components/stable/gux-tabs/gux-tab/gux-tab.less
The main change was to disable the scroll button when at scroll start and end 
From UX:
After the Design System team reviewed the new gux-tabs-beta component, there were a couple fixes needed that we noticed.
* Use the hand cursor when hovering over a tab. 
* When hovering on the overflow arrow buttons, the behavior should align with what is currently implemented in the table component.
* Hover color on button should be Grey-50 
* Arrow icon color should not change to Blue-60 . 
* Disable overflow arrow button when you can't go any further to the left or right (up or down for vertical alignment), which is also similar behavior to what is in the table component. 
* Opacity of the button should be 50%
=> fix(gux-tabs): update gux-tabs to match Spark guidelines

src/components/beta/gux-time-picker/example.html, src/components/beta/gux-time-picker/gux-time-picker.tsx, src/components/beta/gux-time-picker/i18n/en.json, src/components/beta/gux-time-picker/readme.md, src/components/beta/gux-time-picker/tests/gux-time-picker.e2e.ts
COMUI-733
I think the best direction for the gux-time-picker would be to have some way to slot in a `label`, or to incorporate it into the gux-form-field component. Any ideas of what the future is for this component?
This solution is not the best, but allows users to provide a `gux-aria-label` attribute for the `gux-time-picker`. If no aria-label is provided, the default is 'Time Picker'
=> fix(gux-time-picker): give gux-time picker an aria-label attribute

package.json, scripts/check-a11y.js, scripts/list-checked-a11y-components.js
run `npm run check-a11y` and follow the prompts. After finishing the prompts, a markdown file will be put into the specified component's folder. Let me know if you can think of anything to add or change
=> feat(tests): adding new tool for manual accessibility testing

src/components/stable/gux-tabs-advanced/gux-tab-advanced-panel/gux-tab-advanced-panel.less, src/components/stable/gux-tabs/gux-tab-panel/gux-tab-panel.less
COMUI-846
Safari handles focus styling differently from Chrome and Firefox. If this PR looks good I can create the v2 backport PR as well
=> fix(gux-tab-panel): fixed tabpanel outline bug in safari

src/components/stable/gux-dropdown/gux-dropdown.less, src/components/stable/gux-dropdown/gux-dropdown.tsx
COMUI-859
gux-dropdown within a gux-panel closes when the gux-dropdown's scroll button is clicked. If this PR looks good, I will create the v2 backport PR.
Code to recreate bug:
```
<gux-tabs class="example" active-tab="1-1">
<gux-tab-list slot="tab-list">
<gux-tab tab-id="1-1">
<span>Tab Header 1</span>
</gux-tab>
</gux-tab-list>
<gux-tab-panel tab-id="1-1">
<gux-dropdown placeholder="Select..." filterable="true">
<gux-option>1</gux-option>
<gux-option>2</gux-option>
<gux-option>3</gux-option>
<gux-option>4</gux-option>
<gux-option>5</gux-option>
<gux-option>6</gux-option>
<gux-option>7</gux-option>
<gux-option>8</gux-option>
<gux-option>9</gux-option>
<gux-option>10</gux-option>
<gux-option>11</gux-option>
<gux-option>12</gux-option>
<gux-option>13</gux-option> …
```
=> fix(gux-dropdown): gux-dropdown within a gux-panel closes on scroll button click

src/components/beta/gux-tabs-beta/gux-tab-panel-beta/gux-tab-panel-beta.less
=> fix(gux-tab-panel-beta): fixed tabpanel outline shown on click in safari

src/components/stable/gux-tabs/example.html, src/components/stable/gux-tooltip-title/gux-tooltip-title.less
COMUI-910
The tooltip for gux-tabs now wraps long text as expected
**long word:**
=> fix(gux-tooltip-title): long text no longer overflows tab tooltip

src/components/beta/gux-tabs-beta/example.html, src/components/beta/gux-tooltip-title/gux-tooltip-title.less
COMUI-910
backport of https://github.com/MyPureCloud/genesys-webcomponents/pull/649
=> fix(gux-tabs-beta): long text no longer overflows tab tooltip backport

src/components/beta/gux-chart-column/gux-chart-column.less, src/components/beta/gux-tag/gux-tag.less, src/components/stable/gux-tabs-advanced/gux-tab-advanced/gux-tab-advanced.less, src/style/color-palette.less
Issue with aqua-green colour from the secondary colour palette was not passing accessibility checks with the new gux-black-40 text colour in the tag component. Updated to gux-black-30 for accessibility.
=> Feature/com UI 977

package-lock.json, package.json, tsconfig.json
COMUI-984
After merging this, all dependencies will be at `latest`. Dev dependencies will be updated in other PRs
Needed to add `ES2020.Intl` to tsconfig compilerOptions because I was getting this error after installing the latest version of `intl-messageformat`:
```
[0] [ ERROR ]  TypeScript: ./node_modules/@formatjs/ecma402-abstract/types/relative-time.d.ts:35:17
[0]            Namespace 'Intl' has no exported member
[0]            'ResolvedRelativeTimeFormatOptions'.
[0] 
[0]      L34:  fields: LocaleFieldsData;
[0]      L35:  style: Intl.ResolvedRelativeTimeFormatOptions['style'];
[0]      L36:  numeric: Intl.ResolvedRelativeTimeFormatOptions['numeric'];
```
New types for Intl were added in ES2020 https://github.com/microsoft/TypeScript/blob/main/lib/lib.es2020.intl.d.ts …
=> chore(dependencies): update intl-messageformat to latest

src/components/stable/gux-calendar/gux-calendar.tsx
**Description of issue :** 
In gux-datepicker, when the first selected month is December, January displays with wrong year. For example, if we select December 2021, next month is January 2021 instead of January 2022. Happens for 2020, 2019 etc. as well.  This bug is present in v3.0.0-alpha.58.
**Root cause analysis:**
Within the calendar component both of the year values for the header were being picked up via `this.previewValue.getFullYear()`. This logic was returning the year for the first element. So for example if 'December 2019' was the first element then 'this.previewValue.getFullYear()' would be equal to 2019 and thus set January equal to 2019 also even though it should be 2020. This also affected the screen reader text.
**Resolution:**
As a resolution to to this I created a method …
=> fix(calendar): addition of getYearLabel() to fix wrong year displaying in header of calendar

src/components/beta/gux-table/gux-table.light.less
Should I create a story for the cleanup of all beta components and create sub tasks for each component to update all hardcoded pixel sizes and utilise the spacing.less variables. The same goes with typography.
=> fix(table): updating specific pixel sizes to set spacing variables

src/components/stable/gux-datepicker/gux-datepicker.less, src/components/stable/gux-datepicker/gux-datepicker.tsx, src/components/stable/gux-datepicker/tests/__snapshots__/gux-datepicker.spec.ts.snap
**Description of issue:**
When opening the gux-calendar from gux-datepicker, the calendar shows up below the datepicker absolutely positioned. This will cause the entire control to be cut off when there is not enough vertical space in the container for the calendar to appear.
**Root cause analysis:**
The calendar component is positioned absolutely so if the container has not enough space the calender controls will be unavailable to the end user.
**Resolution:**
Implemented popper js within the datepicker component. The datepicker acts as a reference and the calender component acts as the popper element. If there is not enough space in the container the datepicker will either position itself above the reference or below the reference. Also added an offset of 8px between the reference and …
=> fix(datepicker) - implement popper js into datepicker component.

src/components/beta/gux-popover-list/gux-popover-list.less, src/components/stable/gux-popover/gux-popover.less
COMUI-1022
Tab options in `gux-popover-list` were not showing properly in Safari only
=> fix(gux-popover): fix z-index for Safari stacking context bug

src/components/beta/gux-dropdown-v2/gux-dropdown-v2.less, src/components/beta/gux-popup/gux-popup.less
COMUI-1033
Bug showing in newest version of Chrome only
Removed `isolation: isolate` from both `gux-popup` and `gux-dropdown-v2` which solved the problem. Did not seem to cause any regressions in other browsers or stacking context situations. This did not seem to cause the COMUI-562 bug to resurface https://inindca.atlassian.net/browse/COMUI-562.
=> fix(gux-dropdown-v2): fix stacking context bug

.npmrc, Jenkinsfile
I think this should finally fix our NPM publishing credential issues. It's not as tidy as the previous approach, but it should work, as it's based on the IFC build process.
=> build(publish): fix npmrc config for publishing

Docs.Jenkinsfile
The docs build is only triggered by the component job, which handles avoiding build loops. The build
loop check here just causes mainline docs never to build due to the release commit from the
component build.
COMUI-1055
This depends on: https://bitbucket.org/inindca/pipeline-library/pull-requests/304/comui-1055-make-build-loop-check
=> ci(docs): don't skip build on commits from Jenkins

src/components/beta/gux-table/example.html, src/components/beta/gux-table/gux-table.tsx, src/components/beta/gux-table/tests/gux-table.e2e.ts
**Description of issue :** 
For sortable columns in the gux-table component, if there is a child element in the sortable th element, and the user clicks on the child element, the guxsortchanged event does not contain the th's attributes for the columnName and sortDirection.
**RCA:**
In the table component the `columnElement` value was being set to `event.target` which was targeting the inner span tag if present instead of the parent `th` element. 
**Resolution:**
As a resolution to this I applied the `currentTarget` property to the event object instead of `target` property.
https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget
**View changes :** 
https://apps.inindca.com/common-ui-docs/genesys-webcomponents/feature/COMUI-1017
=> fix(table): applied currentTarget property to event object to retrieve parent element instead of child.

Jenkinsfile
In moving to the new web pipeline to publish the component assets, we adopted the new cached asset
mechanism which uses applicaiton-relative paths to fetch assets. Since the components are not an
app, but are included in other apps, these paths were not correct. This changes the build so it will
use a fully qualified URL to look up assets.
COMUI-1063
=> fix(build): fix assets url generation during build process

stencil.config.ts
COMUI-1077
added `experimentalImportInjection` flag to fix lazy load issue with Vite bundler. 
Description of what flag does:
`Experimental flag. Projects that use a Stencil library built using the dist output target may have trouble lazily loading components when using a bundler such as Vite or Parcel. Setting this flag to true will change how Stencil lazily loads components in a way that works with additional bundlers. Setting this flag to true will increase the size of the compiled output. Defaults to false.`
I pulled down the repo that was experiencing the error with loading the stencil components using `vite`. I was able to reproduce the error.  I linked the `genesys-webcomponents` branch with the `experimentalImportInjection` flag set to `true` and it solved the reported problem. …
=> fix(config): add experimentalImportInjection flag

src/components/stable/gux-calendar/gux-calendar.tsx
**Description of issue**
When using the range calendar component option users experienced a weird behaviour if they were to select the last few dates of any given month eg ( `29, 30, 31` ). This issue was happening on both keyboard and mouse controls. An example of this issue would be if you were to open the date-picker on the left you have `January` and on the right you have `February`. If a user was to select the `29,30,31` of January this would cause the right side of the calendar to shift to `March` when it should be `February`. 
**RCA**
After doing some investigation the problem lied within the `calendar` component. Within the render function for the calendar it has different functions which do different things the main functions related to this problem were `getMonthDays()`.  If I …
=> bug(gux-calendar) - datepicker behaves wrongly when we move to the 31st of a month

src/components/beta/gux-loading-message/example.html, src/components/beta/gux-loading-message/gux-loading-message-constants.ts, src/components/beta/gux-loading-message/gux-loading-message-size.types.ts, src/components/beta/gux-loading-message/gux-loading-message.less, src/components/beta/gux-loading-message/gux-loading-message.tsx, src/components/beta/gux-loading-message/readme.md, src/components/beta/gux-loading-message/tests/__snapshots__/gux-loading-message.e2e.ts.snap, src/components/beta/gux-loading-message/tests/__snapshots__/gux-loading-message.spec.ts.snap, src/components/beta/gux-loading-message/tests/gux-loading-message.e2e.ts, src/components/beta/gux-loading-message/tests/gux-loading-message.spec.ts
**Related Story :** 
https://inindca.atlassian.net/browse/COMUI-1096
**Description of task :**
Creation of loading state component.
**Things to note:**
- The body slot is optional.
**Items still to be considered:**
- Name of component.
- Should we include a default option if nothing slotted is supplied ie `<gux-loading-message size="medium" />` and this would contain a default title and possibly a body aswell (use messaging supplied in anatomy).
- From an accessibility standpoint I was thinking the use of `aria-live` might work well here so I have included it in this iteration.
- With the `gux-radial-progress` it requires screen-reader text attribute but would this be redundant in this component as there is a title and body? Potentially add an `aria-hidden` tag.
=> feat(loading-message) - addition of loading message component

src/style/css-custom-properties.less, src/style/spacing.less
Adds gux-prefixed spacing variables. Existing usages of the unprefixed names are not updated, but I am happy to do that as well.
=> feat(css): add gux-prefixed spacing variables

docs/src/component-listing/app.js
COMUI-1119
Links were not opening when docs site was accessed through `common-ui-docs` as an iframed app
This is related to PR in `common-ui-docs` repo https://bitbucket.org/inindca/common-ui-docs/pull-requests/3/comui-1119-update-iframe-coordinator. The version of `iframe-coordinator` being used by `common-ui-docs` was updated to allow popups.
=> docs(links): open external links in new tab

src/components/stable/gux-form-field/components/gux-form-field-checkbox/gux-form-field-checkbox.less, src/components/stable/gux-form-field/components/gux-form-field-checkbox/gux-form-field-checkbox.tsx, src/components/stable/gux-form-field/components/gux-form-field-checkbox/tests/__snapshots__/gux-form-field-checkbox.e2e.ts.snap, src/components/stable/gux-form-field/components/gux-form-field-checkbox/tests/__snapshots__/gux-form-field-checkbox.spec.ts.snap
Related ticket: https://inindca.atlassian.net/browse/COMUI-1166
I am not sure if this change will need to go through the design team but I think it should be added. I currently just added the styling to the `form-field-checkbox` component but this will also need to be applied to the `form-field-radio` component.
"When you have multiple checkboxes or radios stacked and one is using the error slot, it becomes visually confusing what's what. It would be clearer that the error belongs to the checkbox or radio above by aligning to its label rather than its input."
=> style(checkbox): align error message to label instead of input

src/components/stable/gux-tooltip/gux-tooltip.less, src/components/stable/gux-tooltip/gux-tooltip.tsx
Ticket : https://inindca.atlassian.net/browse/COMUI-1103
**Description :** 
When gux-tooltip is added to a gux-button, when we click on that button and either
The button gets programmatically disabled , or,
we follow up with a click outside the button.
we get an issue that the tooltip still appears for that button, and cannot be dismissed by clicking anywhere outside the button. The tooltip can only be disabled by hovering over that button again.
**Res:**
I removed the setTimeout/clearTimeout for the css transition as I dont think it is needed. Instead I updated the transition property to 1s in the css to align with the spark design. I also added a disabled check to the **mouseenter** as when the button or element is disabled on hover it will still display the tooltip. I just check to see …
=> (fix) - Tooltip appears for button when focus not on button, Does not get dismissed by clicking outside

README.md, src/components/beta/gux-flyout-menu/gux-flyout-menu.less, src/components/beta/gux-popover-list/gux-popover-list.less, src/components/beta/gux-table/gux-table-select-menu/gux-table-select-popover/gux-table-select-popover.less, src/components/legacy/gux-dropdown-legacy/gux-dropdown.less, src/components/legacy/gux-form-field-legacy/components/gux-input-color/gux-input-color.less, src/components/stable/gux-advanced-dropdown/gux-advanced-dropdown.less, src/components/stable/gux-datepicker/gux-datepicker.less, src/components/stable/gux-form-field/components/gux-form-field-range/gux-form-field-range.less, src/components/stable/gux-modal/gux-modal.less, src/components/stable/gux-popover/gux-popover.less, src/components/stable/gux-popup/gux-popup.less, src/components/stable/gux-tooltip/gux-tooltip.less, src/style/css-custom-properties.less, src/style/zindex.less
Define CSS variables for z-index values of raised content like
dropdowns, popovers, modals, etc. so that they can be customized within
application styles by overriding the relevant z-index variables as a
rule for a selector containing content with conflicting z-index values.
=> feat(css): overridable z-index variables

src/components/stable/gux-form-field/components/gux-form-field-radio/gux-form-field-radio.less, src/components/stable/gux-form-field/components/gux-form-field-radio/gux-form-field-radio.tsx, src/components/stable/gux-form-field/components/gux-form-field-radio/tests/__snapshots__/gux-form-field-radio.e2e.ts.snap, src/components/stable/gux-form-field/components/gux-form-field-radio/tests/__snapshots__/gux-form-field-radio.spec.ts.snap
Related Task : https://inindca.atlassian.net/browse/COMUI-1166
Align error label with input label
This styling has already been applied to `form-field-checkbox`.
COMUI-1183
=> style(radio): align error label with input label

src/components/beta/gux-blank-state/example.html, src/components/beta/gux-blank-state/gux-blank-state-constants.ts, src/components/beta/gux-blank-state/gux-blank-state.less, src/components/beta/gux-blank-state/gux-blank-state.tsx, src/components/beta/gux-blank-state/gux-blank-state.types.ts, src/components/beta/gux-blank-state/readme.md, src/components/beta/gux-blank-state/tests/__snapshots__/gux-blank-state.spec.ts.snap, src/components/beta/gux-blank-state/tests/gux-blank-state.e2e.ts, src/components/beta/gux-blank-state/tests/gux-blank-state.spec.ts, src/components/beta/gux-button-slot/gux-button-slot.tsx, src/components/beta/gux-button-slot/readme.md
Create message component , relates to task https://inindca.atlassian.net/browse/COMUI-1074.
Open to changing the name of the component if there is a more suitable name.
**Summary :**
- There is no illustrations in this current implementation just the use of icons.
- Should we have default message like the example in figma.
- For accessibility I was thinking aria-live might be a good fit with the polite setting.
=> feat(blank-state) - addition of blank-state component

src/components/stable/gux-form-field/functional-components/gux-form-field-container/gux-form-field-container.less
Add a part attribute to the .gux-form-field-container element so that
apps can override the margin rules that are applied by default to that
element, e.g. if used within a CSS grid where those spacings are applied
via the gap property.
=> feat(css): allow margin overrides on .gux-form-field-container

src/components/stable/gux-toggle/gux-toggle.tsx, src/components/stable/gux-toggle/tests/gux-toggle.e2e.ts
When `preventDefault()` is called on check events, the toggle's state will not change
COMUI-1002
I'll make another PR to backport to V2
=> feat(gux-toggle): enable preventDefault on check events

src/components/stable/gux-toggle/gux-toggle.tsx, src/components/stable/gux-toggle/tests/gux-toggle.e2e.ts
When `preventDefault()` is called on check events, the toggle's state will not change
COMUI-1002
=> V2: feat(gux-toggle): enable preventDefault on check events

src/components/stable/gux-calendar/gux-calendar.tsx, src/components/stable/gux-calendar/tests/gux-calendar.e2e.ts
calendar skipping month for some dates.
Related Task:  https://inindca.atlassian.net/browse/COMUI-1193
**Issue**: Calendar skipping months for some dates. This is due to the calculations happening within `gux-calendar`. The render functions runs twice once for the left side of the calendar and once for the right side of the calendar when you select a date. So for example if I select the 31st of August the calculation will be based off 31 days for the right side also but seeing as september does not have 31 days it will push it out to the next month which results in october being displayed. 
Fix:
Set calculation to be based off the first date in the month regardless of what is selected. 
COMUI-1193
=> fix(calendar): calendar skipping month for some dates

package-lock.json, package.json, stencil.config.ts
This makes the output of test.watch more useful by focusing on failing tests. It has some impact on regular testing in that I could not find a combination of CLI options that would remove test coverage output. So, I removed the text reporters for code coverage. We still generate artifacts for it though, so we could update  Jenkins to track and report on it if we like.
=> test(reporters): improve output for test.watch npm script

REACT_INTEGRATION.md, React.Jenkinsfile, common-webcomponents-react/package-lock.json, common-webcomponents-react/package.json
Two changes here (can separate if need be):
1.  Take `@types/react` as a `peerDependency`/`devDependency` rather than `dependency` - this fixes type issues with projects trying to consume this library using a different version of React.
I think this is a necessary and straightforward fix.
3. Consumers were also having type errors from conflicting minor versions of `genesys-spark-components` and `genesys-spark-components-react`.  (If the react wrapper was built from a newer minor version, its typings would reference GUX elements that didn't exist in the base package).  
This isn't a necessary fix - we can advise consumers to specify versions more tightly (e.g. `~`  not `^`), but this PR changes the relationship to make `genesys-spark-components@X.Y.Z` a dependency of …
=> Change dependencies of the React Wrapper

src/components/stable/gux-dropdown/gux-dropdown.tsx, src/components/stable/gux-listbox/gux-listbox.service.ts, src/components/stable/gux-listbox/gux-listbox.tsx
Related Task : https://inindca.atlassian.net/browse/COMUI-1132
**Issue:**
This issue was identified in angular.
When options are loaded asynchronously the text has whitespace on either side of the text. This will prevent the filter operation from working.
**Resolution:**
Removed whitespace for text content of gux-options.
=> fix(option): remove whitespace from text of gux-options.

src/components/beta/gux-dropdown-multi/gux-dropdown-multi.tsx, src/components/beta/gux-dropdown-multi/readme.md, src/components/stable/gux-popup/gux-popup.tsx, src/components/stable/gux-popup/readme.md
**Related Task:** https://inindca.atlassian.net/browse/COMUI-1254
Addition of `expanded` and `collapsed` event to `gux-dropdown-multi`
**Analysis**
There is no event  available for when a select/dropdown is closed.
**Questions**
1. What would determine the dropdown being closed. Would it be when the dropdown is in a collapsed state or when the entire component has lost focus?
2. Should this also be implemented into `gux-dropdown`
=> feat(dropdown-multi): addition of collapsed and expanded events

src/components/legacy/gux-form-field-legacy/gux-form-field.tsx, src/components/stable/gux-radial-progress/gux-radial-progress.tsx, src/components/stable/gux-radial-progress/tests/gux-radial-progress.spec.ts, src/components/stable/gux-rating/gux-rating.tsx, src/components/stable/gux-tooltip-title/gux-tooltip-title.tsx
Related : https://inindca.atlassian.net/browse/COMUI-1283
Switch to logWarn on a11y errors.
COMUI-1283
=> refactor(components): switch to logWarn on a11y errors

src/components/stable/gux-tooltip-title/gux-tooltip-title.less
Changes styles in gux-tooltip-title to use `@gux-icon-size-global-default` explicitly rather than assuming the icon is 1rem.
=> style(gux-tooltip-title): size icon explicitly instead of assuming 1rem

src/components/stable/gux-form-field/components/gux-form-field-number/gux-form-field-number.less
See discussion and screen captures on https://inindca.atlassian.net/browse/COMUI-1317.
This addresses feedback I got that the step buttons are too small. It trades the 2px padding on the stepper buttons for 4px more width and height of the chevron icons.
Additionally does some more specific flexbox styling to make sure the `<gux-icon>` has no extra descender height from being `inline-flex` by default. This was causing the number input to be slightly taller than other inputs in my app (I think because it was effectively `display: inline` due to the container not being `display: flex`).
=> fix(css): increase step button icon size in gux-form-field-number

package-lock.json, package.json
The failing Jenkins build gives us this error: `fatal: tag 'v3.38.0' already exists`. In this PR, I bumped the version to `3.38.0` to fix the failing build.
I also created [COMUI-1327](https://inindca.atlassian.net/browse/COMUI-1327) to fix the Jenkins issue
=> fix(version): bump version to fix Jenkins build

src/components/beta/gux-pagination-beta/gux-pagination-beta.tsx, src/components/beta/gux-pagination-beta/tests/__snapshots__/gux-pagination-beta.spec.ts.snap, src/components/beta/gux-pagination-beta/tests/gux-pagination-beta.spec.ts, src/components/stable/gux-pagination/gux-pagination.tsx, src/components/stable/gux-pagination/tests/__snapshots__/gux-pagination.spec.ts.snap, src/components/stable/gux-pagination/tests/gux-pagination.spec.ts
**Related Task :** https://inindca.atlassian.net/browse/COMUI-1313
Verified this update with UX. I think the easiest way to do this is just to set `totalItems` to 1. But the downside is that it would represent that there is 1 item in the table even though there is no data in the table. I am not sure if this is a big deal. I think that `totalItems` is only used to calculate the total page count so it should be fine.
=> feat(pagination): default number of pages to 1

src/components/beta/gux-table/gux-table.tsx
**Related ticket :** https://inindca.atlassian.net/browse/COMUI-1339
Currently with the resizing of columns in **gux-table**  there is not a unit supplied when resizing so it returns "Invalid property value" in some other repos. By adding `px` this should hopefully resolve those issues.
Example of wem-webcomponents repository,
=> fix(table): add px unit to columns when scaling

src/components/stable/gux-form-field/functional-components/gux-form-field-fieldset-container/gux-form-field-fieldset-container.less
Same idea as #903 but for .gux-form-field-fieldset-container. Make the baked-in margins overridable via CSS variables. See [COMUI-1362](https://inindca.atlassian.net/browse/COMUI-1362) for more info.
=> feat(css): allow margin overrides on .gux-form-field-fieldset-container

src/components/stable/gux-dismiss-button/gux-dismiss-button.less, src/components/stable/gux-dismiss-button/gux-dismiss-button.tsx, src/components/stable/gux-dismiss-button/gux-dismiss-button.types.ts, src/components/stable/gux-dismiss-button/readme.md
**Related Ticket :**  https://inindca.atlassian.net/browse/COMUI-1373
Currently the `gux-dismiss-button` is absolutely positioned with no way to have it free flowing. Added `isInline` property to allow for this with the default positioning being to the top right of the component.
=> feat(dismiss-button): addition of optional positioning

src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/gux-table-toolbar-custom-action.tsx
Issue : Focus ring is sometimes shown & sometimes not when clicking the buttons.
Reason : `gux-toolbar-custom-action` is rendered inside of `gux-toolbar-action`.
=> fix(table-toolbar): add delegatesFocus to custom action component

src/components/stable/gux-datepicker/gux-datepicker.less
Makes the calendar button display: flex so that the icon within is properly centered.
See #1052 for the same fix to gux-time-picker
=> fix(gux-datepicker): vertically center calendar button

src/components/beta/gux-time-picker/gux-time-picker.less
Makes the clock button `display: flex` so that the icon within is properly centered.
=> fix(gux-time-picker): vertically center clock button

src/components/beta/gux-alert/example.html, src/components/beta/gux-alert/gux-inline-alert.less, src/components/beta/gux-alert/gux-inline-alert.tsx, src/components/beta/gux-alert/readme.md, src/components/stable/gux-tooltip-title/readme.md
Confirmed these changes with UX. Related Ticket : https://inindca.atlassian.net/browse/COMUI-1395
Related Spark docs to be updated accordingly.
`gux-truncate-beta` can be used if the end consumer wishes to truncate the message.
=> feat(inline-alert) - text will now wrap instead of truncating

src/components/stable/gux-button-multi/gux-button-multi.tsx
**Issue** 
Disabled `gux-button` and disabled `gux-multi-button` are different Colours.
**Related Ticket**
https://inindca.atlassian.net/browse/COMUI-1412
**Fix**
In `gux-button-multi` a disabled attribute was applied to both the popup and button element causing an overlap in css. Removed the disabled attribute from popup element.
=> fix(button-multi): align button and button-multi colours for disabled state.

src/components/stable/gux-icon/gux-icon.tsx
Skip validation of decorative/screenreader-text when `this.root.isConnected` is false. This fixes an issue with UIs that use `<gux-icon>` in my app's Mocha unit tests.
=> fix(gux-icon): only validate screenreader-text if attached to a document

src/components/beta/gux-popover-list/gux-popover-list.tsx, src/components/beta/gux-table/gux-sort-control/gux-sort-control.tsx, src/components/beta/gux-table/gux-table-select-menu/gux-table-select-popover/gux-table-header-popover.tsx, src/components/legacy/gux-form-field-legacy/components/gux-input-color/gux-input-color.tsx, src/components/legacy/gux-form-field-legacy/components/gux-input-number/gux-input-number.tsx, src/components/legacy/gux-form-field-legacy/components/gux-input-range/gux-input-range.tsx, src/components/legacy/gux-form-field-legacy/components/gux-input-search/gux-input-search.tsx, src/components/legacy/gux-form-field-legacy/components/gux-input-select/gux-input-select.tsx, src/components/legacy/gux-form-field-legacy/components/gux-input-text-like/gux-input-text-like.tsx, src/components/legacy/gux-form-field-legacy/gux-form-field.tsx, src/components/legacy/gux-list-legacy/gux-list.tsx, src/components/stable/gux-advanced-dropdown/gux-advanced-dropdown.tsx, src/components/stable/gux-content-search/gux-content-search.tsx, src/components/stable/gux-form-field/components/gux-form-field-checkbox/gux-form-field-checkbox.tsx, src/components/stable/gux-form-field/components/gux-form-field-color/gux-form-field-color.tsx, src/components/stable/gux-form-field/components/gux-form-field-dropdown/gux-form-field-dropdown.tsx, src/components/stable/gux-form-field/components/gux-form-field-number/gux-form-field-number.tsx, src/components/stable/gux-form-field/components/gux-form-field-radio/gux-form-field-radio.tsx, src/components/stable/gux-form-field/components/gux-form-field-range/gux-form-field-range.tsx, src/components/stable/gux-form-field/components/gux-form-field-search/gux-form-field-search.tsx, src/components/stable/gux-form-field/components/gux-form-field-select/gux-form-field-select.tsx, src/components/stable/gux-form-field/components/gux-form-field-text-like/gux-form-field-text-like.tsx, src/components/stable/gux-form-field/components/gux-form-field-textarea/gux-form-field-textarea.tsx, src/components/stable/gux-form-field/components/gux-form-field-time-picker/gux-form-field-time-picker.tsx, src/components/stable/gux-popover/gux-popover.tsx, src/utils/decorator/on-mutation.ts, src/utils/decorator/on-resize.ts
Add defensive checks to all invocations of MutationObserver#disconnect() within disconnectedCallback(), as there are cases where disconnectedCallback() is invoked prior to the initialization of the MutationObserver.
=> fix: check MutationObservers before calling disconnect

src/components/stable/gux-tabs-advanced/gux-tab-advanced/gux-tab-advanced.tsx
**Issue**
Enter key does not open dropdown.
**Related Ticket**
https://inindca.atlassian.net/browse/COMUI-1405
I also fixed where it was not focusing the first element when the popover opened via a click.
I think potentially the `gux-context-menu` could be used to replace the current implementation.
=> fix(tabs-advanced): fix issue where "enter" key does not open dropdown

src/components/stable/gux-dropdown/gux-dropdown.tsx
**Related Task:** https://inindca.atlassian.net/browse/COMUI-1312
Change to behaviour of adding option to dropdown with unknown value set. Previously when adding an option to a dropdown with an unknown value set it would not select that value once it was added to the list. Now if that option is added it will be selected once it has been added to the dropdown.
=> refactor(dropdown): change to behaviour of adding option to dropdown with unknown value set

src/components/stable/gux-tabs-advanced/gux-tab-advanced/gux-tab-advanced.less
This PR includes tasks : https://inindca.atlassian.net/browse/COMUI-1416 and https://inindca.atlassian.net/browse/COMUI-1417 
Addition of vertical separator when dropdown options are used. Removal of padding from tooltip-title so that the kebab menu icon and title align correctly.
=> refactor(tabs-advanced): add vertical separator, align text vertically

src/style/focus.less
Add helper CSS classes for applying `.gux-focus-ring-small` styles to a focused or focused-within element, similar to the ones already there that apply the `.gux-focus-ring` styles.
=> feat(css): add -focused and -focused-within classes for small focus ring

src/components/stable/gux-form-field/components/gux-form-field-textarea/gux-form-field-textarea.less
Slotted textarea is too wide & too short  in some instances. Reproducible on the vue-2 playground.
Width seens to be due to box-sizing cascading in or its omission somewhere, similar issue on line-height of a parent could be the height issue.
Simplest fix is to harden the sizing by letting flexbox handle it.
=> fix(textarea): textarea width and height incorrect in some instances

src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/gux-table-toolbar-custom-action.less, src/components/beta/gux-table-toolbar/gux-table-toolbar-menu-button/gux-table-toolbar-menu-button.less, src/components/beta/gux-table-toolbar/gux-table-toolbar-menu-button/gux-table-toolbar-menu-button.tsx, src/components/beta/gux-table-toolbar/gux-table-toolbar-menu-button/readme.md, src/components/beta/gux-table-toolbar/gux-table-toolbar.less, src/components/beta/gux-table-toolbar/gux-table-toolbar.service.tsx, src/components/beta/gux-table-toolbar/gux-table-toolbar.tsx, src/components/beta/gux-table-toolbar/tests/__snapshots__/gux-table-toolbar.spec.ts.snap, src/utils/dom/get-slot.ts
**Related Ticket** : https://inindca.atlassian.net/browse/COMUI-1358
Issues resolved in this PR include the following,
**Vertical bar seperator** : Updated so that the vertical bar only presents itself when there are contextual actions present. Also updated logic to include if contextual actions are the only actions present in the toolbar the vertical bar will not be displayed.
**Menu updates**
- The menu will now dynamically show. If the user doesn't supply any actions to the menu-actions slot the menu will not show until it reaches a condensed state.  
- The menu will show in all states full -> condensed and vice versa if actions have been supplied or that the menu-actions slot exists.
**Console Errors :**  
1. Fixed console errors that were being caused if you were to remove one of the …
=> feat(table-toolbar) - updates to design / bug fixes

src/components/stable/gux-popover/example.html, src/components/stable/gux-popover/gux-popover.less, src/components/stable/gux-popover/gux-popover.tsx, src/components/stable/gux-popover/readme.md, src/components/stable/gux-popover/tests/__snapshots__/gux-popover.spec.ts.snap, src/components/stable/gux-popover/tests/gux-popover.e2e.ts, src/components/stable/gux-popover/tests/gux-popover.spec.ts, src/style/shadows.less
Updates to the popover design include the following : 
- Increased the padding of the wrapper to 20px. Currently there is no token available for 20px so it was requested to do @ spacing-medium  * 1.25.
- New Shadow 40 added to the shadows file and also added to the popover design ( I wasn't sure if a separate PR was needed for this type of change )
-  An optional button slot has also been added where you can have two buttons the spacing between them is 8px and they are right aligned.
- Updated the fonts for the title and content to correct fonts.
- Padding between the sections is 16px from title to content and 20px from content to footer.
- Removal of border on the component itself.
- Update to arrow design on popover. ( UX input needed )
- Dismiss button is now aligned with the popover …
=> feat(popover) - updates to design

src/components/beta/gux-dropdown-multi/gux-dropdown-multi.tsx, src/components/stable/gux-dropdown/gux-dropdown.tsx
**Related Ticket:** https://inindca.atlassian.net/browse/COMUI-1493
Addition of mutation observer to `gux-dropdown`
This fix has already been implemented into `gux-dropdown-multi`. You can view the merged PR here : https://github.com/MyPureCloud/genesys-webcomponents/pull/1073/files
=> fix(dropdown): addition of mutation observer to gux-dropdown

src/components/beta/gux-popover-beta/gux-popover-beta.tsx, src/utils/dom/find-element-by-id.ts
This update to the `for` attribute logic will unblock me in the current `pagination-beta` updates where I am using the `gux-popover-beta` within the shadowDOM of another component. I have tested this locally and it resolves the issue.
If you were wondering how I am using the `popover` this is still WIP but just for clarity : https://github.com/MyPureCloud/genesys-webcomponents/blob/feature/COMUI-1225/src/components/beta/gux-pagination-beta/gux-pagination-buttons-beta/gux-pagination-ellipsis-button/gux-pagination-ellipsis-button.tsx
@MattCheely Edit: getRootNode() works well!
I can implement this into stable popover also once approved.
=> feat(popover-beta): update to "for" attribute to search shadowRoot

src/components/beta/gux-announce/tests/__snapshots__/gux-announce.e2e.ts.snap, src/components/beta/gux-announce/tests/__snapshots__/gux-announce.spec.ts.snap, src/components/beta/gux-announce/tests/gux-announce.e2e.ts, src/components/beta/gux-announce/tests/gux-announce.spec.ts, src/components/beta/gux-loading-message/tests/gux-loading-message.e2e.ts
There were a few questions around accessibility recently & we reported that we were covered by automated Axe tests.
This PR is to bring us in line with the report by adding the a11yCheck to gux-loading-message & gux-announce.
Also added some snapshots to gux-announce while I was there.
=> test(axe): adding 2 axe test to increase coverage

src/components/stable/gux-tooltip/gux-tooltip.tsx
Related Ticket : https://inindca.atlassian.net/browse/COMUI-1544
This should be the final blocker for me on the `pagination-beta` updates. I am using the `tooltip` in the same context as the `popover-beta` where it cannot find the `for` attribute.
WIP branch for clarity : 
https://github.com/MyPureCloud/genesys-webcomponents/blob/9a24ccd14e428b8abca3288ebbab6ae78792a437/src/components/beta/gux-pagination-beta/gux-pagination-buttons-beta/gux-pagination-ellipsis-button/gux-pagination-ellipsis-button.tsx
=> feat(tooltip): addition of findElementByID util to tooltip

src/components/stable/gux-form-field/components/gux-form-field-text-like/gux-form-field-text-like.light.less, src/components/stable/gux-form-field/components/gux-form-field-text-like/gux-form-field-text-like.tsx, src/components/stable/gux-form-field/gux-form-field.light.less
My use case is a number input that uses the "suffix" feature of form-field-text-like
=> feat(form-field-text-like): allow slotted number input

src/components/beta/gux-dropdown-multi/gux-dropdown-multi.less
Prevent text from overlapping in dropdown-multi when `filterable` or `filter-type` are applied.
[COMUI-1510](https://inindca.atlassian.net/browse/COMUI-1510)
[COMUI-1510]: https://inindca.atlassian.net/browse/COMUI-1510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(dropdown-multi): prevent text from overlapping

src/components/beta/gux-badge/example.html, src/components/beta/gux-badge/gux-badge.less, src/components/beta/gux-badge/gux-badge.types.ts, src/components/beta/gux-badge/i18n/en.json, src/components/beta/gux-badge/readme.md, src/components/beta/gux-badge/tests/__snapshots__/gux-badge.e2e.ts.snap, src/components/beta/gux-badge/tests/__snapshots__/gux-badge.spec.ts.snap, src/components/beta/gux-badge/tests/gux-badge.e2e.ts, src/components/beta/gux-badge/tests/gux-badge.spec.ts, src/i18n/translations/en.json
In some cases, designers need to create custom badges where they have a status where the existing colors are not appropriate & they need to differentiate labels.
I've added a new color prop value (custom), to guard against the accidental overriding of existing colors & used the custom properties override pattern used in the input margins.
=> feat(badge): allow custom colors

src/components/beta/gux-time-picker/gux-time-picker.service.tsx, src/components/beta/gux-time-picker/gux-time-picker.tsx, src/components/beta/gux-time-picker/tests/gux-time-picker.service.spec.ts
**Related Ticket:** https://inindca.atlassian.net/browse/COMUI-1437
Open to suggestions on how to further improve the time-picker input keyboard interactions.
A few things which have changed:
I tried to make it more functional like the native time input  although there is slight differences https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time
- I have added a leading `0` to the `12` hour time input before it just displayed the time as eg `9:00` instead of `09:00`. I am not sure was there a reason behind this to begin with ? (Could this be seen as a breaking change)
- Bug **(COMUI-1432)** should be resolved with this change so when typing in a digit the cursor will always start at the end of the input and not the current position of the cursor.
- Bug **(COMUI-1430)** should …
=> feat(time-picker) - bug fixes and improvements

src/components/stable/gux-icon/gux-icon.tsx
Currently TS consumers don't really get autocomplete on iconName because it's effectively just `iconName: string`.  This use a slight TS hack to work around it.  Linked [Typescript/#49220](https://github.com/microsoft/TypeScript/issues/49220) - which may eventually provide a non-hacky fix via JSDoc comment.  (But that PR has been open for almost a year, so I'm not holding my breath)
=> feat(icon): better autocomplete for iconName

packages/genesys-spark-components/src/components/beta/gux-phone-input/services/RegionCountryCodeMap.ts
I went over every region code and country code again to double check. This one was the only mistake.
=> fix(phone-input): fixing country phone code for HU - Hungary

packages/genesys-spark-components/src/components/stable/gux-listbox/options/gux-option-icon/gux-option-icon.less
Updates `gux-option-icon` styling to use margin instead of padding for the space between the icon and the text since the icon's width is assumed not to include that spacing but that's not the case if the icon has `box-sizing: border-box`.
https://inindca.atlassian.net/browse/COMUI-1612
=> fix(dropdown): use margin for spacing beside gux-option-icon icon

packages/genesys-spark-components/src/components/stable/gux-toggle/gux-toggle-slider/gux-toggle-slider.less
The existing toggle slider is built to be a flexbox but isn't assigned as one. The fact that it _isn't_ a flexbox means that the appropriate vertical alignment of its children are vulnerable to host document root styling. That kind of layout issue can be hard to track down.
=> feat(toggle): make gux-toggle-slider a flexbox

packages/genesys-spark-components/src/components/stable/gux-calendar/gux-calendar.less
Align tables flush to start of container.
[COMUI-1579](https://inindca.atlassian.net/browse/COMUI-1579)
[COMUI-1579]: https://inindca.atlassian.net/browse/COMUI-1579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(calendar): align tables flush to start of container

packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar.service.tsx, packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar.tsx
allow for end user to set icon-only
Related Ticket : https://inindca.atlassian.net/browse/COMUI-1558
If a user is using an `icon-only` custom-action the screenreader text of the slotted gux-icon can be used for accessibility.
=> fix(table-toolbar): allow ability to set icon-only on toolbar actions

.gitignore, packages/genesys-spark-components/src/components/beta/gux-time-picker/gux-time-picker.less
Restores the prior `:focus-within` based focus styling for gux-time-picker component. This matches the behavior of gux-form-field-text-like, which is a conceptually similar component to time picker.
https://inindca.atlassian.net/browse/COMUI-1611
=> fix(gux-time-picker): restore :focus-within focus styling

packages/genesys-spark-components/src/components/stable/gux-icon/example.html
There are a lot of icons rendered on the page initially, this is a little more tidier.
=> docs(icon): organise icons into current and legacy tabs

packages/genesys-spark-components/src/components/stable/gux-tabs-advanced/gux-tab-advanced-list/gux-tab-advanced-list.tsx
allow scrolling if dragged element is over scroll button.
This implementation is based on how I think it should work. There currently is no guidance on how it should work.
COMUI-1693
=> fix(tab-advanced-list): allow drag scrolling

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-checkbox/gux-form-field-checkbox.tsx, packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-color/gux-form-field-color.tsx, packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-number/gux-form-field-number.tsx, packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio/gux-form-field-radio.tsx, packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-range/gux-form-field-range.tsx, packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-search/gux-form-field-search.tsx, packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-text-like/gux-form-field-text-like.tsx, packages/genesys-spark-components/src/components/stable/gux-form-field/gux-form-field.service.ts
- Will emit console error if there is no slotted `input` or if element slotted to `input` slot is not valid.
- Will emit console error if `type` provided is incorrect.
COMUI-1559
=> perf(form-field) - Improve error messaging

packages/genesys-spark-components/src/components/stable/gux-icon/gux-icon.service.ts, packages/genesys-spark-components/src/components/stable/gux-icon/tests/gux-icon.service.spec.ts
Fixes an issue that caused the icon fetch caching to not actually coalesce multiple simultaneous calls via getBaseSvgHtml() to a single fetch request, because the logic that retrieved the cached fetch promise awaited that promise instead of returning it immediately.
https://inindca.atlassian.net/browse/COMUI-1723
=> fix(icon): don't await cached icon fetch promises

Jenkinsfile, jenkinsfiles/components.Jenkinsfile, jenkinsfiles/docs.Jenkinsfile, web-apps/genesys-spark-examples/Jenkinsfile
The `CoreUI@genesys.com` mailer doesn't seem to work as expected in Jenkins. I replaced the `CoreUI@genesys.com` mailer with my own email and tested using `useMailerOffMainline=true`. I verified that it did send an email to my email as expected. For now, I have just added all of our emails to the mailer until we can find out why the core ui mailing list isn't receiving emails sent from Jenkins. 
I also added the `chatGroupId` for the Core UI Chat room. If it works as expected, it should notify the chat room when there is a mainline build failure.
=> chore(jenkinsfile): add email and chat notification

packages/genesys-spark-components/src/utils/dom/find-element-by-id.ts
Fixes an infinite loop in the `findElementById()` helper where in some cases a node returns itself from `getRootNode()`. Also in the same case where I observed getRootNode() return itself, rootNode was not a Document so the attempt to call `getElementById()` resulted in an uncaught error. This change also addresses that by checking the `nodeType` and using node.ownerDocument if the node itself is not a document.
https://inindca.atlassian.net/browse/COMUI-1757
=> fix(popover): infinite loop in find-element-by-id

packages/genesys-spark-components/src/components/beta/gux-pagination-beta/gux-pagination-items-per-page-beta/gux-pagination-items-per-page-beta.less, packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-items-per-page/gux-pagination-items-per-page.less
https://inindca.atlassian.net/browse/COMUI-1742
Applied a fixed width to the items per page dropdown within both the `pagination-beta` and stable `pagination` components. The reasoning behind this was that in the issue above if you resize the pagination the dropdown will change sizes which will result in the truncation not being applied as the dropdown has increased by `7px`
The `width` I used was `64px` which is outlined in the figma design for pagination (https://genesysds.zeroheight.com/7978beca0/p/62953d-pagination/b/15a8df). There is no way to change the width of the dropdown so I chose to use the `part` selector to achieve this. I think it is probably reasonable to have this so end consumers can change the size of the dropdown ?
=> fix(pagination): add fixed width to items per page dropdown

packages/genesys-spark-components/src/components/beta/gux-popup-beta/gux-popup-beta.less, packages/genesys-spark-components/src/components/beta/gux-popup-beta/gux-popup-beta.tsx
hide popup element when target element goes out of view.
**Notes**
When implementing this  `floating-ui` uses the `visibility` css property to show and hide the popup container when its goes out of view and comes back into the view. We are also using the `visibility` property within our css for when the user clicks on the target element which causes the `visibility` in the css to be overridden.
The cleanest solution I could think of without causing breakages was to just set the styling through javascript and apply the stying in the necessary places.
Also this change will affect other components which use `popup-beta`
[COMUI-1712](https://inindca.atlassian.net/browse/COMUI-1712)
[COMUI-1712]: https://inindca.atlassian.net/browse/COMUI-1712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhY …
=> fix(gux-popup-beta): hide popup when target element goes out of view

packages/genesys-spark-components/src/utils/dom/find-element-by-id.ts
https://inindca.atlassian.net/browse/COMUI-2135
Refactor the mechanism in find-element-by-id.ts for getting the Document/DocumentFragment instance to its own function that correctly handles the document fragment case. This addresses an issue introduced in the fix for COMUI-2000, which addressed an issue introduced in the fix for COMUI-1757!
https://inindca.atlassian.net/browse/COMUI-2000
https://inindca.atlassian.net/browse/COMUI-1757
=> fix(popover): find-element-by-id tries to call getElementById non-document node

packages/genesys-spark-tokens/data/tokens.json
Renamed the `data_table_items.scrollbar` token since it was causing issues with style-dictionary.
=> fix(token): Renamed data-table scrollbar token

packages/genesys-spark-components/src/components/beta/gux-calendar-beta/components/single/gux-calendar.scss, packages/genesys-spark-components/src/components/beta/gux-calendar-beta/components/single/gux-calendar.tsx, packages/genesys-spark-components/src/components/beta/gux-calendar-beta/components/single/readme.md, packages/genesys-spark-components/src/components/beta/gux-calendar-beta/example.html, packages/genesys-spark-components/src/components/beta/gux-calendar-beta/gux-calendar.light.scss, packages/genesys-spark-components/src/components/beta/gux-calendar-beta/gux-calendar.types.ts, packages/genesys-spark-components/src/components/beta/gux-calendar-beta/i18n/en.json, packages/genesys-spark-components/src/components/beta/gux-calendar-beta/readme.md, packages/genesys-spark-components/src/components/beta/gux-calendar-beta/services/calendar.service.ts, packages/genesys-spark-components/src/components/beta/gux-calendar-beta/services/tests.service.ts, packages/genesys-spark-components/src/components/beta/gux-calendar-beta/tests/gux-calendar.e2e.ts, packages/genesys-spark-components/src/components/beta/gux-calendar-beta/tests/gux-calendar.spec.ts, packages/genesys-spark-components/src/components/beta/gux-date/readme.md, packages/genesys-spark-components/src/components/stable/gux-icon/readme.md, packages/genesys-spark-components/src/i18n/translations/en.json, packages/genesys-spark-components/src/style/style.less
Added a gux-calendar-beta component.
Figma file linked to the JIRA ticket for this PR: https://www.figma.com/file/JKbHmcf4nUF6C7Pj8M6MpY/Spark%3A-Ember-2.0---Core?type=design&node-id=548-28980&mode=design&t=MN4Mz9Uple6OzKWs-0
The current plan is to build a gux-calendar-beta component that will be built from scratch with a fresh perspective. We decided to slot in a date input field but then hide this slotted date input in the UI and instead show custom calendar styling and logic the per gux-calendar-beta component. This is the date/calendar component setup we have decided on going forward.
gux-calendar-beta -> handles single date selection logic
gux-calendar-range-beta -> handles range date selection logic
gux-date-picker-beta (uses gux-calendar-beta internally)
gux-date-picker-range-beta …
=> Calendar beta component

packages/genesys-spark-tokens/data/tokens.json
Modified the secondary and ghost button's hover and active foreground color tokens because they didn't pass the contrast check.
=> [GDS-2065] Fix/button tokens

packages/genesys-spark-components/src/components/stable/gux-icon/gux-icon.tsx
In Firefox, updating the decorative or screenreader-text on a gux-icon that has never had an icon-name set (and triggered code resolved) reports an error to the console. This can be reproduced in the playground by adding a gux-icon without an icon-name set and programmatically altering either the decorative or screenreader-text value. 
My proposed approach is just to check that the baseSvgHtml has already been set before attempting to call the method that uses the baseSvgHtml to update the internal html of the component. If the icon-name is never set, the internals of the component are empty (existing behavior). If the icon-name is set, the same method that is bypassed by my changes will run after the baseSvgHtml is loaded asynchronously.
=> fix(gux-icon): prevent updates to svgHtml if baseSvgHtml is not set

packages/genesys-spark-components/src/components/beta/gux-dropdown-multi/gux-dropdown-multi.less, packages/genesys-spark-components/src/components/beta/gux-popup-beta/gux-popup-beta.tsx, packages/genesys-spark-components/src/components/beta/gux-popup-beta/readme.md, packages/genesys-spark-components/src/components/beta/gux-popup-beta/tests/__snapshots__/gux-popup-beta.spec.ts.snap, packages/genesys-spark-components/src/components/stable/gux-action-button/gux-action-button.tsx, packages/genesys-spark-components/src/components/stable/gux-action-button/tests/__snapshots__/gux-action-button.spec.ts.snap, packages/genesys-spark-components/src/components/stable/gux-advanced-dropdown/gux-advanced-dropdown.less, packages/genesys-spark-components/src/components/stable/gux-button-multi/gux-button-multi.tsx, packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.less, packages/genesys-spark-components/src/components/stable/gux-listbox-multi/readme.md, packages/genesys-spark-components/src/components/stable/gux-listbox/readme.md
https://inindca.atlassian.net/browse/COMUI-2137
The issues we are currently seeing in the dropdown are linked to a new feature which was added to `gux-popup` which was to allow the lists of action and multi button to extend past its reference. To do this the `floating-ui` implementation was altered in order to achieve this. You can see the changes in this PR https://github.com/MyPureCloud/genesys-webcomponents/pull/1214/files
**Fix**
In this fix I am just verifying the components tag name. If the component is neither an action button nor a multi button then the default floating ui implementation will be used.
**Notes**
Seeing as the popup-beta component has to accommodate for multiple components which include dropdown / multi buttons etc if a request comes in to alter the floating ui …
=> fix(popup): fix floating ui implementation

packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar-action/readme.md, packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/gux-table-toolbar-custom-action.tsx, packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/readme.md, packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar-menu-button/gux-table-toolbar-menu-button.tsx, packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar-menu-button/readme.md, packages/genesys-spark-components/src/components/beta/gux-table-toolbar/readme.md, packages/genesys-spark-components/src/components/beta/gux-table-toolbar/tests/__snapshots__/gux-table-toolbar.spec.ts.snap, packages/genesys-spark-components/src/components/stable/gux-tooltip-title/readme.md, packages/genesys-spark-components/src/components/stable/gux-tooltip/readme.md
addition of tooltip when actions are in icon-only state
[COMUI-1713](https://inindca.atlassian.net/browse/COMUI-1713)
I was not sure about the `menu-actions` button should that always have a tooltip since it technically is always just an icon.
I opted for the `menu-actions` to always have a tooltip.
[COMUI-1713]: https://inindca.atlassian.net/browse/COMUI-1713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(table-toolbar): addition of tooltip when actions are in icon-only mode.
