src/components/beta/gux-tabs/gux-tab/gux-tab.less, src/components/beta/gux-tabs/gux-tabs.less
=> fix(gux-tab): fix style issues in gux-tab

.gitignore, src/components/stable/gux-list/example.html, src/components/stable/gux-list/gux-list.less, src/components/stable/gux-list/gux-list.tsx
fixed an over general css style
COMUI-256
=> fix(gux-list): fixed an over general css style

.gitignore, src/components/stable/gux-toggle/example.html, src/components/stable/gux-toggle/gux-toggle.less
=> fix(gux-toggle): fixed css issues

.github/workflows/main.yml
I need to see if there's a way to test this prior to merging.
=> ci(github): add basic test/lint checks in github workflows

src/components/stable/gux-advanced-dropdown/i18n/ar.json, src/components/stable/gux-datepicker/i18n/ar.json, src/components/stable/gux-modal/i18n/ar.json, src/components/stable/gux-notification-toast/i18n/ar.json, src/components/stable/gux-notification-toast/i18n/es-es.json, src/components/stable/gux-notification-toast/i18n/fr-ca.json, src/components/stable/gux-pagination/gux-pagination-buttons/i18n/ar.json, src/components/stable/gux-popover/i18n/ar.json, src/components/stable/gux-simple-toast/i18n/ar.json, src/components/stable/gux-simple-toast/i18n/es-es.json, src/components/stable/gux-simple-toast/i18n/fr-ca.json, src/components/stable/gux-spin-button/i18n/ar.json, src/components/stable/gux-text-field/i18n/ar.json
Translation Process Automation generated string (DO NOT EDIT): [src/components/stable/gux-advanced-dropdown/i18n/ar.json,src/components/stable/gux-datepicker/i18n/ar.json,src/components/stable/gux-modal/i18n/ar.json,src/components/stable/gux-notification-toast/i18n/ar.json,src/components/stable/gux-notification-toast/i18n/es-es.json,src/components/stable/gux-notification-toast/i18n/fr-ca.json,src/components/stable/gux-pagination/gux-pagination-buttons/i18n/ar.json,src/components/stable/gux-popover/i18n/ar.json,src/components/stable/gux-simple-toast/i18n/ar.json,src/components/stable/gux-simple-toast/i18n/es-es.json,src/components/stable/gux-simple-toast/i18n/fr-ca.json,src/components/stable/gux-spin-button/i18n/ar.json,src/components/stable/gux-text-field/i18n/ar.json]
=> chore(translations): translation updates

src/components/stable/gux-datepicker/example.html, src/components/stable/gux-datepicker/gux-datepicker.less, src/components/stable/gux-datepicker/gux-datepicker.tsx, src/components/stable/gux-text-label/gux-text-label.less
fixed styling of date range labels
COMUI-267
=> fix(gux-datepicker): fixed styling of date range labels

docs/src/component-viewer/app.js, docs/src/component-viewer/panels/events.js, docs/src/components-spec.json, docs/src/styles/component-viewer.less
event now display as notiications
COMUI-268
=> docs(event-notifications): event now display as notifications

src/style/css-custom-properties.less, src/style/spacing.less, stencil.config.ts
added spacing styles to export
COMUI-193
=> feat(styles): added spacing styles to export

docs/src/components-spec.json, src/common-utils.ts, src/components/beta/gux-tooltip/example.html, src/components/beta/gux-tooltip/gux-tooltip.less, src/components/beta/gux-tooltip/gux-tooltip.tsx, src/components/beta/gux-tooltip/readme.md, src/components/beta/gux-tooltip/tests/__snapshots__/gux-tooltip.spec.ts.snap, src/components/beta/gux-tooltip/tests/gux-tooltip.e2e.ts, src/components/beta/gux-tooltip/tests/gux-tooltip.spec.ts
reduced the gux-tooltip API
COMUI-160
=> refactor(gux-tooltip): reduced the gux-tooltip API

src/components/stable/gux-calendar/tests/gux-calendar.spec.ts
fixed test that was broken for dates during oct-dec
COMUI-284
=> test(gux-calendar): fixed test that was broken for dates during oct-dec

docs/src/components-spec.json, src/style/examples/spacing.html
added a spacing example
COMUI-193
=> chore(css): added a spacing example

Jenkinsfile, docs/src/components-spec.json, src/components/beta/gux-tag/example.html, src/components/beta/gux-tag/gux-tag.less, src/components/beta/gux-tag/gux-tag.tsx, src/components/beta/gux-tag/i18n/en.json, src/components/beta/gux-tag/readme.md, src/components/beta/gux-tag/tests/__snapshots__/gux-tag.spec.ts.snap, src/components/beta/gux-tag/tests/gux-tag.e2e.ts, src/components/beta/gux-tag/tests/gux-tag.spec.ts, src/components/stable/gux-icon/readme.md
=> feat(tag): add tag component

src/common-enums.ts, src/components/beta/gux-tag/gux-tag.tsx, src/components/beta/gux-tag/gux-tag.types.ts, src/components/stable/gux-text-field/gux-text-field.tsx, src/components/stable/gux-text-field/readme.md
only export component class from component file
COMUI-286
=> build(stencil): only export component class from component file

docs/src/components-spec.json, src/components/beta/gux-table-beta/example.html, src/components/beta/gux-table-beta/gux-row-select/gux-row-select.tsx, src/components/beta/gux-table-beta/gux-row-select/readme.md, src/components/beta/gux-table-beta/gux-row-select/tests/gux-row-select.spec.ts, src/components/beta/gux-table-beta/gux-table.less, src/components/beta/gux-table-beta/gux-table.tsx, src/components/beta/gux-table-beta/gux-table.types.ts, src/components/beta/gux-table-beta/readme.md, src/components/beta/gux-table-beta/tests/gux-table.e2e.ts, src/components/beta/gux-table-beta/tests/gux-table.spec.ts, src/components/stable/gux-checkbox/readme.md
=> Table component row selection

src/components/beta/form/gux-form-field-beta/gux-form-field-beta.less, src/components/beta/form/gux-form-field-beta/gux-form-field-beta.tsx, src/components/beta/form/gux-form-field/components/gux-error-message-beta/gux-error-message-beta.less, src/components/beta/form/gux-form-field/components/gux-error-message-beta/gux-error-message-beta.tsx, src/components/beta/form/gux-form-field/components/gux-input-color-beta/gux-input-color-beta.less, src/components/beta/form/gux-form-field/components/gux-input-color-beta/gux-input-color-beta.tsx, src/components/beta/form/gux-form-field/components/gux-input-range-beta/gux-input-range-beta.less, src/components/beta/form/gux-form-field/components/gux-input-range-beta/gux-input-range-beta.tsx, src/components/beta/gux-command-palette/gux-command-palette.less, src/components/beta/gux-command-palette/gux-command-palette.tsx, src/components/beta/gux-command-palette/tests/gux-command-palette.e2e.ts, src/components/beta/gux-panel-frame/gux-panel-frame.less, src/components/beta/gux-panel-frame/gux-panel-frame.tsx, src/components/beta/gux-radial-loading/gux-radial-loading.less, src/components/beta/gux-radial-loading/gux-radial-loading.tsx, src/components/beta/gux-radial-loading/tests/__snapshots__/gux-radial-progress.e2e.ts.snap, src/components/beta/gux-radial-loading/tests/__snapshots__/gux-radial-progress.spec.ts.snap, src/components/beta/gux-search/gux-search.tsx, src/components/beta/gux-side-panel/gux-side-panel.less, src/components/beta/gux-side-panel/gux-side-panel.tsx, src/components/beta/gux-side-panel/tests/gux-side-panel.e2e.ts, src/components/beta/gux-side-panel/tests/gux-side-panel.spec.ts, src/components/beta/gux-tag/gux-tag.less, src/components/stable/gux-page-loading-spinner/tests/__snapshots__/gux-page-loading-spinner.e2e.ts.snap, src/components/stable/gux-radial-progress/tests/__snapshots__/gux-radial-progress.e2e.ts.snap
prefixed classes in beta components with gux-
COMUI-273
=> refactor(style): prefixed classes in beta components with gux-

REACT_INTEGRATION.md, README.md
=> docs: add documentation on integrating web components with react

src/components/stable/gux-calendar/gux-calendar.less, src/components/stable/gux-calendar/gux-calendar.tsx
small css and style changes
COMUI-305
=> fix(gux-calendar): small css and style changes

package.json
run dev build before unit tests so generated classes can be used in spec files
=> Fix unit test run

src/style/color-palette.less, src/style/color.less, src/style/css-custom-properties.less, src/style/examples/color.html
removed gux-mid-grey
COMUI-327
=> fix(color-palette): removed gux-mid-grey

src/components/stable/gux-popover/gux-popover.tsx
arrow now padded from the popover edge
COMUI-247
=> fix(gux-popover): arrow now padded from the popover edge

src/components/stable/gux-advanced-dropdown/gux-advanced-dropdown.tsx
dropdown icon now works as expected
COMUI-335
=> fix(gux-advanced-dropdown): dropdown icon now works as expected

src/components/stable/gux-dropdown/gux-dropdown.tsx
Fix https://inindca.atlassian.net/browse/COMUI-338
=> fix(gux-dropdown): do not filter dropdown while opening, until value is edited

src/components/stable/gux-dropdown/gux-dropdown.tsx
Fix change from COMUI-339 that adds extra change event.
=> fix(gux-dropdown): avoid extra change event

src/components/beta/gux-tooltip/example.html, src/components/beta/gux-tooltip/gux-tooltip.tsx
=> refactor(gux-tooltip): added a new example

src/components/stable/gux-modal/example.html
We added the dynamic size previously to unblock a specific feature. Now we're documenting it both
here and on the spark website.
COMUI-304
=> docs(modal): document the dynamic modal size

README.md
=> fix(readme): fixed install code

src/style/typography.less
fixed h4 line-height and font weight
COMUI-364
=> fix(typography): fixed h4 line-height and font weight

src/components/stable/gux-calendar/gux-calendar.tsx
fixed chinese weekday name abbreviations
COMUI-359
=> fix(calendar): fixed chinese weekday name abbreviations

src/components/stable/gux-dropdown/readme.md, src/components/stable/gux-modal/example.html, src/components/stable/gux-modal/gux-modal.tsx, src/components/stable/gux-modal/readme.md
changed default size to dynamic
BREAKING CHANGE: modal default size changed from small to dynamic
COMUI-344
=> refactor(modal): changed default size to dynamic

package.json
fixed clean npm script so it works on a fresh clone
COMUI-368
=> fix(build): fixed clean npm script

src/components/stable/gux-datepicker/example.html, src/components/stable/gux-datepicker/gux-datepicker.tsx
input now works for all date separators
COMUI-358
=> fix(datepicker): input now works for all date separators

src/components/stable/gux-action-button/gux-action-button.less, src/components/stable/gux-action-button/gux-action-button.tsx, src/components/stable/gux-action-button/tests/gux-action-button.e2e.ts, src/components/stable/gux-button/gux-button.less, src/style/color-palette.less, src/style/mixins.less
updated button colors
COMUI-380
=> refactor(color): updated button colors

src/components/beta/gux-tabs/gux-tab/gux-tab.tsx, src/components/beta/gux-tabs/gux-tab/readme.md, src/components/beta/gux-tabs/gux-tabs.tsx, src/utils/dom/event-is-from.spec.ts, src/utils/dom/event-is-from.ts
options toggle now propagates click events
COMUI-371
=> fix(gux-tab): options toggle now propagates click events

src/components/beta/gux-tabs/gux-tab/gux-tab.tsx
fixed popover arrow positioning
COMUI-397
=> fix(gux-tab): fixed popover arrow positioning

src/components/stable/gux-modal/example.html
events now displayed in docs event panel
COMUI-398
=> fix(gux-modal): events now displayed in docs event panel

Jenkinsfile, package-lock.json, package.json
removed @purecloud/web-app-deploy dependency
COMUI-393
=> ci(optional-dependencies): removed @purecloud/web-app-deploy dependency

src/components/legacy/gux-color-picker-legacy/gux-color-picker.less, src/components/stable/gux-form-field/components/gux-input-color/gux-input-color.less
popup panel moved down to be similar to dropdown
COMUI-325
=> fix(color-input): popup panel moved down to be similar to dropdown

package-lock.json, src/components/stable/gux-pagination/example.html, src/components/stable/gux-pagination/gux-pagination-buttons/gux-pagination-buttons.less, src/components/stable/gux-pagination/gux-pagination-buttons/gux-pagination-buttons.tsx, src/components/stable/gux-pagination/gux-pagination-item-counts/gux-pagination-item-counts.less, src/components/stable/gux-pagination/gux-pagination-items-per-page/gux-pagination-items-per-page.less, src/components/stable/gux-pagination/gux-pagination.less
updated colors based on UX input
COMUI-388
=> fix(gux-pagination): updated colors based on UX input

src/components/beta/gux-table/gux-table.less
updated colors based on input from UX
COMUI-373
=> fix(gux-table): updated colors

src/components/stable/gux-toggle/gux-toggle.less
updated colors based on UX input
COMUI-375
=> fix(gux-toggle): updated colors

src/components/stable/gux-action-button/example.html, src/components/stable/gux-action-button/gux-action-button.tsx
actions menu closes when button is disabled
COMUI-413
=> fix(gux-action-button): actions menu closes when button is disabled

src/components/stable/gux-form-field/components/gux-input-number/gux-input-number.less, src/components/stable/gux-form-field/components/gux-input-number/gux-input-number.tsx, src/components/stable/gux-form-field/components/gux-input-number/tests/__snapshots__/gux-input-number.spec.ts.snap, src/components/stable/gux-form-field/components/gux-input-number/tests/gux-input-number.spec.ts, src/components/stable/gux-form-field/components/gux-input-range/tests/gux-input-range.spec.ts, src/components/stable/gux-form-field/components/gux-input-text-like/gux-input-text-like.less, src/components/stable/gux-form-field/components/gux-input-text-like/gux-input-text-like.tsx, src/components/stable/gux-form-field/components/gux-input-text-like/tests/__snapshots__/gux-input-text-like.spec.ts.snap, src/components/stable/gux-form-field/components/gux-input-text-like/tests/gux-input-text-like.spec.ts, src/components/stable/gux-form-field/example.html, src/components/stable/gux-switch/tests/gux-switch.spec.ts
fixed disabled states
COMUI-416 COMUI-418
=> fix(gux-form-field): fixed disabled states

package-lock.json, package.json, src/components/legacy/gux-slider-legacy/gux-slider.tsx, src/components/legacy/gux-slider-legacy/readme.md, src/components/stable/gux-form-field/components/gux-input-range/gux-input-range.tsx
range ui now update on programatic value change
COMUI-367
=> fix(range): range ui now update on programatic value change

src/components/stable/gux-toggle/example.html, src/components/stable/gux-toggle/gux-toggle.less, src/components/stable/gux-toggle/gux-toggle.tsx, src/components/stable/gux-toggle/gux-toggle.types.ts, src/components/stable/gux-toggle/readme.md, src/components/stable/gux-toggle/tests/gux-toggle.e2e.ts
the label can now be positioned left or right (default)
COMUI-420
=> feat(gux-toggle): added label position property

.github/workflows/main.yml, Jenkinsfile
added ability to release maintenance releases
COMUI-424
=> ci(releases): added ability to release maintenance releases

.github/workflows/main.yml, src/components/stable/gux-popover/gux-popover.tsx
fixed class name missing gux prefix
COMUI-425
(cherry picked from commit a16d0f7c584f8c1c9ab67fc812ab8651dc937392)
=> fix(gux-popover): fixed class name missing gux prefix

.github/workflows/main.yml
added maintenance branch checks
(cherry picked from commit 737be248c30b2abe495f87f85baa5606a616aafc)
=> build(github): added maintenance branch checks

src/components/stable/gux-dropdown/gux-dropdown.less
update colors based on UX input
COMUI-378
=> fix(gux-dropdown): update colors based on UX input

src/components/beta/gux-table/gux-table.less, src/components/beta/gux-tooltip/gux-tooltip.less, src/components/stable/gux-action-toast/gux-action-toast.less, src/components/stable/gux-modal/gux-modal.less
fixed incorrect fade parameters
COMUI-436
=> fix(fade): fixed incorrect fade parameters

package.json, src/components/beta/gux-table/gux-row-select/readme.md, src/components/legacy/gux-checkbox-legacy/readme.md, src/components/stable/gux-content-search/gux-content-search.less
updated colors based on UX input
COMUI-384
=> fix(gux-content-search): updated colors

src/components/beta/gux-table/gux-row-select/readme.md, src/components/legacy/gux-checkbox-legacy/readme.md, src/components/stable/gux-datepicker/example.html, src/components/stable/gux-datepicker/gux-datepicker.service.tsx, src/components/stable/gux-datepicker/gux-datepicker.tsx, src/components/stable/gux-datepicker/gux-datepicker.types.ts, src/components/stable/gux-datepicker/tests/gux-datepicker.service.spec.ts, src/components/stable/gux-datepicker/tests/gux-datepicker.spec.ts
fixed input bugs
COMUI-358
https://apps.inintca.com/common-ui-docs/genesys-webcomponents/feature/COMUI-358/gux-datepicker.html
=> fix(gux-date-picker): fixed input bugs

src/components/stable/gux-form-field/components/gux-input-range/gux-input-range.tsx, src/components/stable/gux-form-field/components/gux-input-range/readme.md, src/components/stable/gux-form-field/example.html, src/components/stable/gux-form-field/gux-form-field.tsx, src/components/stable/gux-form-field/readme.md
added valueDisplaySuffix property
COMUI-444
=> feat(gux-input-range): added valueDisplaySuffix property

package-lock.json, src/components/stable/gux-datepicker/example.html, src/components/stable/gux-datepicker/gux-datepicker.service.tsx, src/components/stable/gux-datepicker/gux-datepicker.tsx, src/components/stable/gux-datepicker/tests/__snapshots__/gux-datepicker.spec.ts.snap, src/components/stable/gux-datepicker/tests/gux-datepicker.e2e.ts, src/components/stable/gux-datepicker/tests/gux-datepicker.service.spec.ts, src/components/stable/gux-datepicker/tests/gux-datepicker.spec.ts
fixed month increment at end of month
COMUI-439
=> fix(gux-date-picker): fixed month increment at end of month

src/components/stable/gux-tooltip/example.html, src/components/stable/gux-tooltip/gux-tooltip.less
fixed tooltip layout issue
COMUI-457
=> fix(gux-tooltip): fixed tooltip layout issue

src/components/beta/gux-search/example.html, src/components/beta/gux-search/gux-search.less
fixed css issue related to v2 migration
COMUI-456
=> fix(gux-search-beta): fixed css issue related to v2 migration

src/components/stable/gux-form-field/components/gux-input-range/gux-input-range.less
=> fix(gux-form-field): fixed range css bug

src/components/stable/gux-tabs/gux-tabs.tsx
=> fix(gux-tabs): fix tabs flickering when changing browser zoom

src/components/stable/gux-action-button/gux-action-button.less, src/components/stable/gux-button/gux-button.less
Set a font-size for gux-action-button so it can be used by child gux-action-items when they inherit
font-size.
COMUI-462
=> fix(gux-action-button): set font-size for gux-action-button

src/components/beta/gux-table/example.html, src/components/beta/gux-table/gux-table.tsx
all row selector now unchecked when no rows in table
COMUI-464
=> fix(gux-table): all row selector now unchecked when no rows in table

src/style/color-palette.less, src/style/css-custom-properties.less, src/style/examples/color.html
added missing colors
COMUI-454
=> fix(color-palette): added missing colors

scripts/generate-start-of-week-file.js
added ending newline character so output file has no lint or format errors
COMUI-463
=> style(generate-start-of-week-file): added ending newline character

COMPONENT_DESIGN.md, src/components/beta/gux-flyout-menu/gux-flyout-menu.tsx, src/components/beta/gux-flyout-menu/gux-menu/gux-submenu/gux-submenu.tsx, src/components/beta/gux-search/gux-search.tsx, src/components/beta/gux-time-picker/gux-time-picker.tsx, src/components/legacy/gux-radio-group-legacy/gux-radio-group.tsx, src/components/legacy/gux-radio-legacy/gux-radio.tsx, src/components/legacy/gux-slider-legacy/gux-slider.tsx, src/components/legacy/gux-spin-button-legacy/gux-spin-button.tsx, src/components/legacy/gux-text-field-legacy/gux-text-field.tsx, src/components/stable/gux-advanced-dropdown/dropdown-option/gux-dropdown-option.tsx, src/components/stable/gux-content-search/gux-content-search.tsx, src/components/stable/gux-form-field/components/gux-input-color/gux-input-color.tsx, src/components/stable/gux-form-field/components/gux-input-number/gux-input-number.tsx, src/components/stable/gux-form-field/components/gux-input-text-like/gux-input-text-like.tsx, src/components/stable/gux-form-field/components/gux-input-textarea/gux-input-textarea.tsx, src/components/stable/gux-list/gux-list.tsx, src/components/stable/gux-tooltip/gux-tooltip.tsx
updated code in preparation for stenciljs@v2 update
COMUI-468
=> fix(dependencies): updated code in preparation for stenciljs@v2 update

src/components/stable/gux-form-field/components/gux-input-number/gux-input-number.less, src/components/stable/gux-form-field/components/gux-input-text-like/gux-input-text-like.less, src/components/stable/gux-form-field/components/gux-input-textarea/gux-input-textarea.less, src/components/stable/gux-form-field/example.html
=> fix(gux-input-number): fix styling

src/components/stable/gux-form-field/components/gux-input-checkbox/gux-input-checkbox.less, src/components/stable/gux-form-field/components/gux-input-radio/gux-input-radio.less
checkbox and radio button icons updated
COMUI-505
=> fix(gux-form-field): checkbox and radio button icons updated

src/components/stable/gux-form-field/components/gux-input-textarea/example.html, src/components/stable/gux-form-field/components/gux-input-textarea/gux-input-textarea.less, src/components/stable/gux-form-field/components/gux-input-textarea/gux-input-textarea.tsx, src/components/stable/gux-form-field/components/gux-input-textarea/gux-input-textarea.types.ts, src/components/stable/gux-form-field/components/gux-input-textarea/readme.md, src/components/stable/gux-form-field/components/gux-input-textarea/tests/__snapshots__/gux-input-textarea.e2e.ts.snap, src/components/stable/gux-form-field/components/gux-input-textarea/tests/__snapshots__/gux-input-textarea.spec.ts.snap, src/components/stable/gux-form-field/components/gux-input-textarea/tests/gux-input-textarea.e2e.ts, src/components/stable/gux-form-field/components/gux-input-textarea/tests/gux-input-textarea.spec.ts, src/components/stable/gux-form-field/example.html, src/components/stable/gux-form-field/gux-form-field.tsx, src/components/stable/gux-form-field/readme.md, src/style/typography.less
component can now auto resize
COMUI-481
=> feat(gux-input-textarea): component can now auto resize

docs/src/component-listing/app.js, docs/src/styles/component-listing.less, docs/src/styles/component-viewer.less
This PR includes the following updates
- Ability to filter components list by name
- Resizable Preview Area
- Better scrolling behaviour on right panel
=> New features added for the component previewer

src/components/stable/gux-button/example.html, src/components/stable/gux-button/gux-button.less
=> fix(gux-button): added icon buttons

src/components/stable/gux-datepicker/gux-datepicker.tsx, src/components/stable/gux-datepicker/tests/__snapshots__/gux-datepicker.spec.ts.snap
fixed nesting of elements
COMUI-506
=> fix(gux-datepicker): fixed nesting of elements

package-lock.json, package.json, src/components/beta/gux-flyout-menu/gux-flyout-menu.less, src/components/beta/gux-flyout-menu/gux-menu/gux-submenu/gux-submenu.less, src/components/beta/gux-table/gux-table.less, src/components/beta/gux-tag/gux-tag.less, src/components/legacy/gux-color-picker-legacy/gux-color-picker.less, src/components/legacy/gux-slider-legacy/gux-slider.less, src/components/legacy/gux-text-field-legacy/gux-text-field.less, src/components/stable/gux-button/gux-button.less, src/components/stable/gux-calendar/gux-calendar.less, src/components/stable/gux-dropdown/gux-dropdown.less, src/components/stable/gux-form-field/components/gux-input-color/components/gux-color-select/gux-color-select.less, src/components/stable/gux-form-field/components/gux-input-color/gux-input-color.less, src/components/stable/gux-form-field/components/gux-input-number/gux-input-number.less, src/components/stable/gux-form-field/components/gux-input-range/gux-input-range.less, src/components/stable/gux-form-field/components/gux-input-select/gux-input-select.less, src/components/stable/gux-form-field/components/gux-input-text-like/gux-input-text-like.less, src/components/stable/gux-form-field/components/gux-input-textarea/gux-input-textarea.less, src/components/stable/gux-modal/gux-modal.less, src/components/stable/gux-notification-toast/gux-notification-toast.less, src/components/stable/gux-popover/gux-popover.less, src/components/stable/gux-tooltip/gux-tooltip.less, src/style/mixins.less
- added 4px border-radius
- increased border shadow to shadow-20 (modal increased to shadow-30)
- border color changed to gux-grey-30
=> Feature/COMUI-514 Component Modernization

docs/package-lock.json, docs/package.json, docs/src/component-listing/app.js, docs/src/component-viewer/app.js, docs/src/index.html, docs/src/viewer-template.html, docs/webpack.config.js, package-lock.json, package.json
update stencil core to v2
COMUI-473
=> build(dependencies): updates in preparation from Stencil upgrade

docs/src/index.html, docs/src/viewer-template.html
fixed module loading script url
COMUI-521
=> fix(demos): fixed module loading script url

src/components/stable/gux-action-toast/gux-action-toast.less, src/components/stable/gux-list/gux-list.less
These were missed with the initial component modernization work. Also removed theme styling in gux-list.less
=> feature/COMUI-514: component modernization for action button and action toast

src/components/beta/gux-tag/example.html, src/components/beta/gux-tag/gux-tag.less
invalid color prop now displays as default
COMUI-493
=> fix(gux-tag): invalid color prop now displays as default

src/components/beta/gux-panel-frame/gux-panel-frame.less, src/components/beta/gux-panel-frame/gux-panel-frame.tsx, src/components/beta/gux-panel-frame/readme.md, src/components/beta/gux-panel-frame/tests/__snapshots__/gux-panel-frame.e2e.ts.snap, src/components/beta/gux-panel-frame/tests/__snapshots__/gux-panel-frame.spec.ts.snap, src/components/beta/gux-panel-frame/tests/gux-panel-frame.e2e.ts, src/components/beta/gux-panel-frame/tests/gux-panel-frame.spec.ts, src/utils/dom/has-slot.ts
light refactor and added more tests
COMUI-146
=> refactor(gux-panel-frame): light refactor and added more tests

src/components/stable/gux-button/example.html, src/components/stable/gux-button/gux-button.less
button text correctly overflowing with ellipsis
COMUI-522
=> fix(gux-button): button text correctly overflowing with ellipsis

package-lock.json, src/components/beta/gux-command-palette/example.html, src/components/beta/gux-command-palette/gux-command-palette.less, src/components/beta/gux-command-palette/gux-command-palette.tsx, src/components/beta/gux-command-palette/readme.md, src/components/beta/gux-command-palette/tests/gux-command-palette.e2e.ts, src/components/beta/gux-search/readme.md, src/components/stable/gux-advanced-dropdown/gux-advanced-dropdown.less, src/components/stable/gux-advanced-dropdown/gux-advanced-dropdown.tsx, src/components/stable/gux-advanced-dropdown/readme.md, src/components/stable/gux-advanced-dropdown/tests/__snapshots__/gux-advanced-dropdown.spec.ts.snap, src/components/stable/gux-advanced-dropdown/tests/gux-advanced-dropdown.e2e.ts, src/components/stable/gux-advanced-dropdown/tests/gux-advanced-dropdown.spec.ts, src/components/stable/gux-form-field/components/gux-input-search/readme.md, src/components/stable/gux-form-field/readme.md, src/components/stable/gux-tooltip/tests/gux-tooltip.spec.ts, src/i18n/index.ts, src/utils/array/async-filter.ts, src/utils/dom/get-closest-element.ts, stencil.config.ts, tests/setupTests.js
removed uses of gux-search-beta in components
COMUI-523
=> feat(gus-search-beta): removed uses of gux-search-beta in components

src/components/beta/gux-command-palette/gux-command-palette.tsx, src/components/beta/gux-command-palette/tests/gux-command-palette.e2e.ts
=> test(gux-command-palette): fixed flaky tests

src/components/stable/gux-tooltip/gux-tooltip.tsx
recalculate position before showing
COMUI-534
=> fix(gux-tooltip): recalculate position before showing

src/components/beta/gux-table/example.html, src/components/beta/gux-table/gux-all-row-select/gux-all-row-select.less, src/components/beta/gux-table/gux-all-row-select/gux-all-row-select.tsx, src/components/beta/gux-table/gux-all-row-select/readme.md, src/components/beta/gux-table/gux-all-row-select/tests/gux-all-row-select.spec.ts, src/components/beta/gux-table/gux-row-select/gux-row-select.less, src/components/beta/gux-table/gux-table.less, src/components/beta/gux-table/gux-table.tsx, src/components/beta/gux-table/i18n/en.json, src/components/legacy/gux-checkbox-legacy/readme.md, src/components/stable/gux-form-field/components/gux-input-checkbox/gux-input-checkbox.less, src/components/stable/gux-form-field/components/gux-input-radio/gux-input-radio.less, src/components/stable/gux-form-field/readme.md
stopped using legacy component
COMUI-437
=> feat(gux-row-select): stopped using legacy component

docs/src/component-viewer/app.js, docs/webpack.config.js, package-lock.json, package.json
Ability to run accessibility tests is added to the docs project.
It is enabled only in the **development** mode.
=> chore(accessibility-axelive): axe-live is implemented to run accessibility tests

src/components/beta/gux-flyout-menu/gux-flyout-menu.less, src/components/beta/gux-flyout-menu/gux-menu/gux-submenu/gux-submenu.less, src/components/legacy/gux-color-picker-legacy/gux-color-picker.less, src/components/legacy/gux-slider-legacy/gux-slider.less, src/components/stable/gux-action-toast/gux-action-toast.less, src/components/stable/gux-calendar/gux-calendar.less, src/components/stable/gux-dropdown/gux-dropdown.less, src/components/stable/gux-form-field/components/gux-input-color/components/gux-color-select/gux-color-select.less, src/components/stable/gux-form-field/components/gux-input-range/gux-input-range.less, src/components/stable/gux-list/gux-list.less, src/components/stable/gux-modal/gux-modal.less, src/components/stable/gux-notification-toast/gux-notification-toast.less, src/components/stable/gux-popover/gux-popover.less, src/components/stable/gux-tooltip/gux-tooltip.less, src/style/examples/shadows.html, src/style/mixins.less, src/style/shadows.less, src/style/style.less, stencil.config.ts
For ticket COMUI-529
Moved the shadow styles to their own file, then went through to everywhere that used the shadows to make sure the imports matched this new file.
Created shadows.html to demonstrate the shadows.
=> Moved shadow styles to shadows.less and created shadows.html

src/components/beta/gux-dropdown-v2/gux-dropdown-v2.less
fixed missed merge conflict
COMUI-529
=> fix(gux-dropdown-v2): fixed missed merge conflict

src/tests/usage-tracking.spec.ts, src/usage-tracking.ts
changed version tracking object
COMUI-538
(cherry picked from commit 5f7c7901f3dc81cb2890c50d32181e1cb914a0de)
=> fix(user-tracking): changed version tracking object

scripts/generate-versions-file
Fixed a undefined variable "error"
Error screenshot from the pipeline
=> build(generate-versions): fixed a undefined variable "error"

docs/webpack.config.js, scripts/generate-versions-file
allow cors and move away from gmsc
=> build(deploy): allow cors and move away from gmsc

src/components/stable/gux-form-field/components/gux-input-search/example.html, src/components/stable/gux-form-field/components/gux-input-search/gux-input-search.less
**After Fix:**
**Before Fix:**
=> fix(gux-input-search): fixed styling issue when rendering for smaller width

src/components/stable/gux-dropdown/example.html, src/components/stable/gux-dropdown/gux-dropdown.tsx, src/components/stable/gux-icon/icons/add-circle.svg
value attribute now works as expected
COMUI-542
=> fix(gux-dropdown): value attribute now works as expected

docs/src/component-listing/app.js, docs/src/styles/component-listing.less
added Sparks logo to docs site
COMUI-539
=> feat(sparks-logo): added Spark logo to docs site

src/components/stable/gux-accordion/example.html, src/components/stable/gux-accordion/gux-accordion.less, src/components/stable/gux-accordion/gux-accordion.tsx, src/components/stable/gux-accordion/gux-accordion.types.ts, src/components/stable/gux-accordion/readme.md
added toggle icon position property
COMUI-545
=> feat(accordion): added toggle icon position property

src/components/stable/gux-accordion/gux-accordion.less
set explicit text color on accordion header text
COMUI-557
=> fix(accordion): set explicit text color on accordion header text

src/components/beta/gux-dropdown-v2/gux-dropdown-v2.less, src/components/beta/gux-popup/gux-popup.less, src/components/beta/gux-table/gux-table.less
fixed stacking context
COMUI-562
=> fix(gux-table): fixed stacking context

playground/angular-v12/src/app/app.component.html, playground/angular-v12/src/app/app.component.ts, src/components/beta/gux-accordion/gux-accordion-section/gux-accordion-section.less, src/components/beta/gux-accordion/gux-accordion-section/gux-accordion-section.tsx, src/components/beta/gux-accordion/gux-accordion-section/gux-accordion-section.types.ts, src/components/beta/gux-accordion/gux-accordion-section/readme.md, src/components/beta/gux-accordion/gux-accordion.less, src/components/beta/gux-accordion/gux-accordion.tsx, src/components/beta/gux-accordion/readme.md, src/components/stable/gux-accordion/example.html, src/components/stable/gux-accordion/gux-accordion.service.tsx, src/components/stable/gux-accordion/gux-accordion.tsx, src/components/stable/gux-accordion/gux-accordion.types.ts, src/components/stable/gux-accordion/readme.md, src/components/stable/gux-accordion/tests/__snapshots__/gux-accordion.spec.ts.snap, src/components/stable/gux-accordion/tests/gux-accordion.spec.ts, src/components/stable/gux-icon/readme.md
I don't think it is possible to fix this issue in the current `gux-accordion` component.
I have created a new beta component with a low migration overhead that solves the issue.
I have also refactored the `gux-accordion` component code to make it simpler to follow as I was investigating this issue.
=> gux-accordion with ng-if

src/components/stable/gux-toggle/gux-toggle-slider/gux-toggle-slider.less
fixed toggle styling
COMUI-571
=> fix(toggle): fixed toggle styling

docs/src/utils/debounce.js, src/components/legacy/gux-radio-group-legacy/gux-radio-group.tsx, src/components/legacy/gux-text-field-legacy/tests/gux-text-field.spec.ts, src/components/stable/gux-action-button/gux-action-button.tsx, src/components/stable/gux-content-search/tests/gux-content-search-beta.spec.ts, src/components/stable/gux-popover/tests/gux-popover.spec.ts, src/components/stable/gux-rating/gux-rating.less, src/components/stable/gux-rating/gux-rating.tsx, src/components/stable/gux-rating/tests/__snapshots__/gux-rating.spec.ts.snap, src/components/stable/gux-rating/tests/gux-rating.e2e.ts, src/components/stable/gux-rating/tests/gux-rating.spec.ts, src/utils/date/from-iso-time-string.spec.ts, src/utils/dom/event-is-from.spec.ts, src/utils/dom/when-event-is-from.spec.ts
fixed empty star color
COMUI-569
=> fix(rating): fixed empty star color

src/components/beta/gux-button-slot/gux-button-slot.less, src/components/beta/gux-command-palette/gux-command-palette.less, src/components/beta/gux-popup/gux-popup.tsx, src/components/stable/gux-list/gux-list.less, src/components/stable/gux-list/list-divider/gux-list-divider.less, src/components/stable/gux-list/list-item/gux-list-item.less, src/components/stable/gux-list/list-item/gux-list-item.tsx
=> fix(action-button): fixed styling

src/components/stable/gux-form-field/components/gux-input-color/components/gux-color-select/gux-color-select.less, src/components/stable/gux-form-field/components/gux-input-color/gux-input-color.less
COMUI-573 align gux-input-color with Spark
=> fix(gux-input-color): fixed styling

src/components/beta/gux-panel-frame/example.html, src/components/stable/gux-modal/example.html
moved primary button in modal and panel-frame to left side in docs examples
Hover color change to black-50 is handled by dismiss button component
COMUI-576
=> fix(modal): fixed styling

src/components/beta/gux-dropdown-v2/gux-dropdown-v2.less, src/components/stable/gux-dropdown/gux-dropdown.less
Updated hover color of icon to black-50
Also had to change the default icon color to black-90
Changed focus state to focus-ring from mixins to allow for 1px gap
Reduced margin between dropdown and menu to 2px
=> fix(dropdown): fixed styling

src/components/beta/gux-table/gux-table.less, src/components/beta/gux-table/gux-table.tsx, src/components/beta/gux-table/readme.md, src/components/stable/gux-button/readme.md
=> fix(gux-table): fixed style to align with Spark

src/components/stable/gux-calendar/gux-calendar.less, src/components/stable/gux-calendar/gux-calendar.tsx, src/components/stable/gux-datepicker/gux-datepicker.less, src/components/stable/gux-datepicker/gux-datepicker.tsx, src/components/stable/gux-datepicker/tests/__snapshots__/gux-datepicker.spec.ts.snap
=> fix(gux-datepicker): fixed style to align with Spark guidelines 

src/components/stable/gux-content-search/gux-content-search.less, src/components/stable/gux-form-field/components/gux-input-search/example.html, src/components/stable/gux-form-field/components/gux-input-search/gux-input-search.less
fixed styling on centent and form field search components
COMUI-579
=> fix(search): fixed styling

src/components/stable/gux-tabs/gux-tab/gux-tab.less
fixed tab options button size
COMUI-592
=> fix(tabs): fixed tab options button size

package-lock.json, package.json
moved vega module from devDependencies to dependencies
COMUI-627
=> build(npm): moved vega module from devDependencies to dependencies

src/components/beta/gux-popup/gux-popup.tsx
fixed action button dropdown positioning
COMUI-626
=> fix(action-button): fixed action button dropdown positioning

src/components/beta/gux-popup/example.html, src/components/stable/gux-action-button/example.html, src/components/stable/gux-action-button/gux-action-button.less
fixed dropdown stacking order
COMUI-624
=> fix(action-button): fixed dropdown stacking order

src/components/stable/gux-popover/gux-popover.tsx, src/components/stable/gux-tabs/gux-tab/gux-tab.tsx
fixed tab options click away functionality
COMUI-591
=> fix(tabs): fixed tab options click away functionality

src/components/stable/gux-text-label/example.html, src/components/stable/gux-text-label/gux-text-label.tsx, src/components/stable/gux-text-label/tests/gux-text-label.e2e.ts, src/components/stable/gux-text-label/tests/gux-text-label.spec.ts
removed references to gux-text-field-legacy
COMUI-610
=> fix(text-label): removed references to gux-text-field-legacy

src/components/stable/gux-form-field/components/gux-input-number/readme.md, src/components/stable/gux-form-field/components/gux-input-select/readme.md, src/components/stable/gux-form-field/components/gux-input-text-like/readme.md
=> fix(form-field): fixed readme files

src/components/beta/gux-button-multi/example.html, src/components/beta/gux-button-multi/gux-button-multi.less, src/components/beta/gux-button-multi/gux-button-multi.tsx, src/components/beta/gux-button-multi/readme.md, src/components/beta/gux-button-slot/readme.md, src/components/beta/gux-popup/readme.md, src/components/stable/gux-icon/readme.md, src/components/stable/gux-list/readme.md
added gux-button-multi component
COMUI-561
=> feat(gux-button-multi): added gux-button-multi component

src/components/legacy/gux-text-field-legacy/readme.md, src/components/stable/gux-datepicker/gux-datepicker.less, src/components/stable/gux-datepicker/gux-datepicker.tsx, src/components/stable/gux-datepicker/readme.md, src/components/stable/gux-datepicker/tests/__snapshots__/gux-datepicker.spec.ts.snap, src/components/stable/gux-datepicker/tests/gux-datepicker.e2e.ts, src/components/stable/gux-datepicker/tests/gux-datepicker.spec.ts, src/components/stable/gux-text-label/readme.md
removed dependency on text-field=legacy component
COMUI-407
=> fix(datepicker): removed dependency on text-field=legacy component

package.json, scripts/list-shadow-explicitly-set.js, src/components/legacy/gux-checkbox-legacy/gux-checkbox.tsx, src/components/legacy/gux-color-option-legacy/gux-color-option.tsx, src/components/legacy/gux-color-picker-legacy/gux-color-picker.tsx, src/components/legacy/gux-color-select-legacy/gux-color-select.tsx, src/components/legacy/gux-radio-group-legacy/gux-radio-group.tsx, src/components/legacy/gux-radio-legacy/gux-radio.tsx, src/components/legacy/gux-slider-legacy/gux-slider.tsx, src/components/legacy/gux-spin-button-legacy/gux-spin-button.tsx, src/components/legacy/gux-switch-legacy/gux-switch.tsx, src/components/legacy/gux-text-field-legacy/gux-text-field.tsx, src/components/stable/gux-text-label/gux-text-label.tsx
updated the script that lists which components have shadow explicitly set
COMUI-597
=> fix(shadow-dom): update script

src/components/stable/gux-tooltip/example.html, src/components/stable/gux-tooltip/gux-tooltip.less, src/components/stable/gux-tooltip/gux-tooltip.tsx, src/style/style.less
=> feat(gux-tooltip): prep to enabled shadowdom

src/components/stable/gux-text-highlight/example.html, src/components/stable/gux-text-highlight/gux-text-highlight.tsx
explicitly set shadow to false
COMUI-642
=> fix(text-highlight): explicitly set shadow to false

src/components/beta/gux-accordion/gux-accordion-section/gux-accordion-section.tsx, src/components/beta/gux-accordion/gux-accordion-section/readme.md, src/components/stable/gux-accordion/example.html
added open prop to accordion section
COMUI-640
=> feat(accordion): added open prop to accordion section

src/components/beta/gux-error-message-beta/gux-error-message-beta.less, src/components/beta/gux-error-message-beta/gux-error-message-beta.tsx, src/components/beta/gux-error-message-beta/readme.md, src/components/beta/gux-error-message-beta/tests/__snapshots__/gux-error-message-beta.spec.ts.snap
fixed slot issue in form-field component
COMUI-597
=> fix(error-message): fixed slot issue in form-field component

src/components/stable/gux-accordion/gux-accordion.tsx
explicitly opted out of shadow dom
COMUI-647
=> fix(accordion): explicitly opted out of shadow dom

src/components/stable/gux-action-toast/gux-action-toast.less, src/components/stable/gux-action-toast/gux-action-toast.tsx
prepare component for enabling shadow dom
COMUI-649
=> fix(action-toast): prepare component for enabling shadow dom

src/components/stable/gux-simple-toast/gux-simple-toast.less
prepared component for convertion to shadow dom
COMUI-646
=> fix(simple-toast): prepared component for convertion to shadow dom

src/components/stable/gux-notification-toast/gux-notification-toast.less
prepare component for enabling shadow dom
COMUI-648
=> fix(notification-toast): prepare component for enabling shadow dom

src/components/stable/gux-dropdown/example.html, src/components/stable/gux-dropdown/gux-dropdown.tsx, src/components/stable/gux-dropdown/gux-option/gux-option.tsx, src/components/stable/gux-dropdown/tests/gux-dropdown.spec.ts
setSelection now called on mutation of options
COMUI-644
=> feat(dropdown): setSelection now called on mutation of options

src/components/stable/gux-action-button/example.html, src/components/stable/gux-action-button/gux-action-button.tsx, src/components/stable/gux-action-button/gux-action-item/gux-action-item.less, src/components/stable/gux-action-button/gux-action-item/gux-action-item.tsx, src/components/stable/gux-action-button/gux-action-item/readme.md, src/components/stable/gux-list/gux-list.tsx, src/components/stable/gux-list/list-item/readme.md
fixed action item disabled state
COMUI-638
=> fix(action-item): fixed action item disabled state

src/components/stable/gux-dropdown/gux-dropdown.tsx, src/components/stable/gux-dropdown/gux-option/gux-option.tsx, src/components/stable/gux-dropdown/gux-option/readme.md, src/components/stable/gux-dropdown/gux-option/tests/gux-option.spec.ts, src/components/stable/gux-text-highlight/readme.md
removed option highlighting
COMUI-656
=> fix(dropdown): removed option highlighting

src/components/stable/gux-toggle/gux-toggle-slider/gux-toggle-slider.less
fixed checkmark positioning
COMUI-655
=> fix(toggle): fixed checkmark positioning

src/components/beta/gux-table/example.html
added more complete table sorting example
COMUI-659
=> docs(table): added more complete table sorting example

src/components/stable/gux-form-field/components/gux-input-checkbox/tests/gux-input-checkbox.e2e.ts, src/components/stable/gux-form-field/components/gux-input-color/tests/gux-input-color.e2e.ts, src/components/stable/gux-form-field/components/gux-input-number/tests/gux-input-number.e2e.ts, src/components/stable/gux-form-field/components/gux-input-radio/tests/gux-input-radio.e2e.ts, src/components/stable/gux-form-field/components/gux-input-range/tests/gux-input-range.e2e.ts, src/components/stable/gux-form-field/components/gux-input-search/tests/gux-input-search.e2e.ts, src/components/stable/gux-form-field/components/gux-input-select/tests/gux-input-select.e2e.ts, src/components/stable/gux-form-field/components/gux-input-text-like/tests/gux-input-text-like.e2e.ts, src/components/stable/gux-form-field/components/gux-input-textarea/tests/gux-input-textarea.e2e.ts, src/components/stable/gux-form-field/tests/gux-form-field.e2e.ts
=> test(gux-form-field): add e2e a11y tests to gux-form-field components

playground/angular-v12/src/app/app.component.html, playground/angular-v12/src/app/app.component.ts, playground/angular-v12/src/app/app.module.ts, playground/vue-2/src/App.vue, playground/vue-2/src/components/HelloWorld.vue, playground/vue-3/index.html, src/components/beta/gux-error-message-beta/gux-error-message-beta.tsx
The angular playground now reproduces the error.
=> chore(playground): updated playgrounds to reproduce error

package-lock.json, src/components/stable/gux-modal/gux-modal.tsx, src/components/stable/gux-modal/readme.md, src/components/stable/gux-modal/tests/gux-modal.e2e.ts
added trap-focus property so trapping foxus is now optional
COMUI-693
=> feat(modal): added trap-focus property

src/components/beta/gux-dropdown-v2/gux-dropdown-v2.tsx, src/components/stable/gux-pagination/gux-pagination-items-per-page/tests/__snapshots__/gux-pagination-items-per-page.spec.ts.snap, src/components/stable/gux-pagination/tests/__snapshots__/gux-pagination.spec.ts.snap
COMUI-707
regression from the gux-dropdown-v2 filter PR https://github.com/MyPureCloud/genesys-webcomponents/pull/398/files
=> fix(gux-dropdown-v2): fixed issue where gux-pagination not showing value in dropdown

src/components/beta/gux-accordion/gux-accordion-section/gux-accordion-section.less, src/components/beta/gux-accordion/gux-accordion-section/gux-accordion-section.tsx, src/components/beta/gux-accordion/gux-accordion-section/readme.md, src/components/stable/gux-accordion/example.html
sections can now be disabled
COMUI-698
=> feat(accordion): sections can now be disabled

Jenkinsfile, package.json
prepare for alpha releases of v3
COMUI-706
=> feat(release): prepare for alpha releases of v3

src/components/beta/gux-dropdown-v2/gux-dropdown-v2.tsx
removed unnecessary code
COMUI-707
=> fix(dropdown): removed unnecessary code

Jenkinsfile
v2 should still be the deployed  branch for now
COMUI-711
=> fix(docs): v2 should still be the deployed  branch for now

src/components/beta/gux-button-multi/gux-button-multi.less, src/components/beta/gux-button-multi/gux-button-multi.tsx, src/components/beta/gux-button-multi/tests/gux-button-multi.e2e.ts, src/components/legacy/gux-command-palette-legacy/gux-command-palette.less, src/components/legacy/gux-command-palette-legacy/gux-command-palette.tsx, src/components/stable/gux-action-button/gux-action-button.less, src/components/stable/gux-action-button/gux-action-button.tsx, src/components/stable/gux-action-button/gux-action-item/gux-action-item.less, src/components/stable/gux-action-button/gux-action-item/gux-action-item.tsx, src/components/stable/gux-action-button/tests/__snapshots__/gux-action-button.spec.ts.snap, src/components/stable/gux-action-button/tests/gux-action-button.e2e.ts, src/components/stable/gux-action-button/tests/gux-action-button.spec.ts, src/components/stable/gux-list/gux-list.less, src/components/stable/gux-list/gux-list.tsx, src/components/stable/gux-list/list-divider/gux-list-divider.less, src/components/stable/gux-list/list-divider/gux-list-divider.tsx, src/components/stable/gux-list/list-item/gux-list-item.less, src/components/stable/gux-list/list-item/gux-list-item.tsx, src/components/stable/gux-list/list-item/tests/gux-list-item.e2e.ts, src/components/stable/gux-list/tests/__snapshots__/gux-list.e2e.ts.snap, src/components/stable/gux-list/tests/gux-list.e2e.ts, src/components/stable/gux-popover/tests/gux-popover.e2e.ts, tests/setupAxeTests.js
explicitly set shadow dom on list component and dependencies
COMUI-696
=> feat(list): explicitly set shadow dom on list component and dependencies

src/components/stable/gux-pagination/gux-pagination.tsx, src/components/stable/gux-pagination/tests/__snapshots__/gux-pagination.spec.ts.snap, src/components/stable/gux-pagination/tests/gux-pagination.spec.ts
better handle invalid current page values
COMUI-716
=> fix(pagination): better handle invalid current page values

src/components/stable/gux-pagination/tests/__snapshots__/gux-pagination.spec.ts.snap
=> test(gux-pagination): fix failing snapshot test

src/components/stable/gux-form-field/components/gux-input-range/gux-input-range.less
small styling change
COMUI-699
=> fix(input-range): small styling change

src/components/stable/gux-disclosure-button/gux-disclosure-button.less, src/components/stable/gux-disclosure-button/gux-disclosure-button.tsx, src/components/stable/gux-disclosure-button/readme.md, src/components/stable/gux-disclosure-button/tests/__snapshots__/gux-disclosure-button.e2e.ts.snap, src/components/stable/gux-disclosure-button/tests/__snapshots__/gux-disclosure-button.spec.ts.snap, src/components/stable/gux-disclosure-button/tests/gux-disclosure-button.e2e.ts, src/components/stable/gux-disclosure-button/tests/gux-disclosure-button.spec.ts
=> feat(disclosure-button): enabled shadow dom

src/components/beta/gux-button-slot/gux-button-slot.less, src/components/beta/gux-button-slot/gux-button-slot.tsx, src/components/beta/gux-button-slot/readme.md, src/components/beta/gux-button-slot/tests/__snapshots__/gux-button-slot.e2e.ts.snap, src/components/beta/gux-button-slot/tests/__snapshots__/gux-button-slot.spec.ts.snap, src/components/beta/gux-button-slot/tests/gux-button-slot.e2e.ts, src/components/beta/gux-button-slot/tests/gux-button-slot.spec.ts
=> feat(button-slot): enabled shadow dom

docs/migrations/v3/readme.md, src/components/stable/gux-modal/gux-modal.tsx
trap-focus prop now defaults to true
COMUI-727
=> feat(modal): trap-focus prop now defaults to true

src/components/stable/gux-calendar/gux-calendar.less, src/components/stable/gux-datepicker/gux-datepicker.less
global gux-sr-only is not used by components anymore
COMUI-744
=> fix(css): global gux-sr-only is not used by components anymore

src/components/beta/gux-side-panel/buttons/gux-side-panel-button.tsx, src/components/beta/gux-side-panel/gux-side-panel.tsx
explicitly set shadow to false
COMUI-742
=> feat(side-panel): explicitly set shadow to false

docs/migrations/v3/readme.md, src/components/stable/gux-datepicker/example.html, src/components/stable/gux-datepicker/gux-datepicker.service.ts, src/components/stable/gux-datepicker/gux-datepicker.tsx, src/components/stable/gux-datepicker/readme.md
label prop now only accepts a string
COMUI-702
=> feat(datepicker): label prop now only accepts a string

.github/workflows/main.yml, Jenkinsfile, src/components/beta/gux-panel-frame/example.html, src/components/beta/gux-panel-frame/gux-panel-frame.less, src/components/beta/gux-panel-frame/gux-panel-frame.tsx, src/components/beta/gux-panel-frame/tests/__snapshots__/gux-panel-frame.e2e.ts.snap, src/components/beta/gux-panel-frame/tests/__snapshots__/gux-panel-frame.spec.ts.snap, src/components/beta/gux-panel-frame/tests/gux-panel-frame.e2e.ts
=> feat(panel-frame): enabled shadow dom

src/components/stable/gux-calendar/gux-calendar.tsx, src/components/stable/gux-calendar/readme.md, src/components/stable/gux-datepicker/gux-datepicker.tsx, src/components/stable/gux-disclosure-button/readme.md
Fixed a style issue where certain dates were not showing the 'selected' style. Also fixed an issue where reopening the calendar will not show the month with the first selected date. There are screenshots and more detailed reproduction steps in the ticket: [COMUI-749](https://inindca.atlassian.net/browse/COMUI-749)
I will also make a backport PR for v2 since this was a reported bug
=> fix(gux-datepicker): fixed date selection bugs

src/components/stable/gux-modal/gux-modal.tsx
focusTrap prop is now updatable
COMUI-739
=> feat(gux-modal): focusTrap prop is now updatable

src/components/legacy/gux-command-palette-legacy/tests/gux-command-palette.e2e.ts, src/components/stable/gux-disclosure-button/readme.md, src/components/stable/gux-dropdown/example.html, src/components/stable/gux-dropdown/gux-dropdown.tsx, src/components/stable/gux-dropdown/tests/gux-dropdown.e2e.ts
now not focusable when disabled
COMUI-753
=> fix(gux-dropdown): now not focusable when disabled

src/components/stable/gux-calendar/gux-calendar.tsx, src/components/stable/gux-calendar/readme.md, src/components/stable/gux-datepicker/gux-datepicker.tsx
backport of https://github.com/MyPureCloud/genesys-webcomponents/pull/557
=> fix(gux-datepicker): fixed datepicker date selection bugs

src/components/stable/gux-toggle/gux-toggle-slider/gux-toggle-slider.less, src/components/stable/gux-toggle/gux-toggle-slider/gux-toggle-slider.tsx, src/components/stable/gux-toggle/gux-toggle-slider/readme.md, src/components/stable/gux-toggle/gux-toggle.tsx, src/components/stable/gux-toggle/i18n/en.json, src/components/stable/gux-toggle/tests/__snapshots__/gux-toggle.spec.ts.snap, src/components/stable/gux-toggle/tests/gux-toggle.e2e.ts
=> fix(gux-toggle): fix nested interactive a11y violation

src/components/stable/gux-radial-progress/example.html, src/components/stable/gux-radial-progress/gux-radial-progress.less, src/components/stable/gux-radial-progress/gux-radial-progress.service.ts, src/components/stable/gux-radial-progress/gux-radial-progress.tsx, src/components/stable/gux-radial-progress/gux-radial-progress.types.ts, src/components/stable/gux-radial-progress/readme.md, src/components/stable/gux-radial-progress/tests/gux-radial-progress.service.spec.ts
=> feat(gux-radial-progress): added scale prop

src/components/beta/gux-dropdown-v2/example.html, src/components/beta/gux-dropdown-v2/gux-dropdown-v2.less, src/components/beta/gux-dropdown-v2/gux-option-v2/gux-option-v2.less
fixed selected item overflow
COMUI-765
(cherry picked from commit 5361819effe167ed8e66d95478fc5228abe5db7f)
=> fix(gux-dropdown-v2): fixed selected item overflow

src/components/beta/gux-dropdown-v2/gux-dropdown-v2.less, src/components/stable/gux-advanced-dropdown/gux-advanced-dropdown.less, src/components/stable/gux-dropdown/gux-dropdown.less
fixed styling differences between dropdown components
COMUI-757
=> fix(dropdowns): fixed styling differences between dropdown components

src/components/stable/gux-modal/gux-modal.less
[COMUI-828](https://inindca.atlassian.net/browse/COMUI-828)
backport of https://github.com/MyPureCloud/genesys-webcomponents/pull/586
=> fix(gux-modal): fix max-height style

src/components/stable/gux-modal/gux-modal.less
[COMUI-828](https://inindca.atlassian.net/browse/COMUI-828)
=> fix(gux-modal): fix max-height for modal sizes

src/components/beta/gux-tag/gux-tag.less, src/components/beta/gux-tag/gux-tag.tsx, src/components/beta/gux-tag/tests/__snapshots__/gux-tag.e2e.ts.snap, src/components/beta/gux-tag/tests/__snapshots__/gux-tag.spec.ts.snap, src/components/beta/gux-tag/tests/gux-tag.e2e.ts, src/components/beta/gux-tag/tests/gux-tag.spec.ts
=> feat(tag-beta): enabled shadow dom

src/components/beta/gux-popup/gux-popup.tsx
=> fix(gux-popup): fix popup alignment

src/components/beta/gux-popup/gux-popup.tsx
=> fix(gux-popup): fix alignment of popup, backport to v2

A11Y_TESTING.md
=> docs(a11y): add documentation for accessibility testing

src/components/stable/gux-dropdown/gux-dropdown.less, src/components/stable/gux-dropdown/gux-dropdown.tsx
gux-dropdown within a gux-panel closes on scroll button click -- backport to v2
COMUI-859
=> fix(gux-dropdown): gux-dropdown within a gux-panel bug

src/components/stable/gux-button/gux-button.less
added specificity to secondary button css
COMUI-858
=> fix(button): added specificity to secondary button css

src/components/beta/gux-time-picker/gux-time-picker.tsx, src/components/beta/gux-time-picker/tests/gux-time-picker.e2e.ts, src/components/beta/gux-time-picker/tests/gux-time-picker.spec.ts
COMUI-880
Fixing a regression in v3. Could not select a time in the dropdown on click
=> fix(gux-time-picker-beta) fix time picker on click bug

src/components/beta/gux-tag/a11yManualChecklist.md, src/components/beta/gux-tag/example.html, src/components/beta/gux-tag/gux-tag.less, src/components/beta/gux-tag/gux-tag.tsx, src/components/beta/gux-tag/i18n/en.json, src/components/beta/gux-tag/tests/__snapshots__/gux-tag.spec.ts.snap, src/components/beta/gux-tag/tests/gux-tag.e2e.ts, src/components/stable/gux-icon/gux-icon.tsx, src/style/mixins.less, src/style/typography.less
improved components accessibility
COMUI-794 COMUI-817
=> fix(tag): improved components accessibility

src/components/beta/gux-chart-donut/gux-chart-donut.tsx, src/components/beta/gux-chart-pie/gux-chart-pie.tsx
enabled shadow dom
COMUI-864 COMUI-865
=> feat(chart): enabled shadow dom

src/components/stable/gux-calendar/gux-calendar.less, src/components/stable/gux-calendar/gux-calendar.tsx, src/components/stable/gux-calendar/tests/gux-calendar.spec.ts, src/components/stable/gux-datepicker/gux-datepicker.less, src/components/stable/gux-datepicker/gux-datepicker.tsx, src/components/stable/gux-datepicker/tests/__snapshots__/gux-datepicker.spec.ts.snap, src/components/stable/gux-datepicker/tests/gux-datepicker.e2e.ts
enabled shadow dom
COMUI-871 COMUI-873
=> feat(datepicker): enabled shadow dom

src/components/beta/gux-time-picker/gux-time-picker.less, src/components/beta/gux-time-picker/gux-time-picker.tsx, src/components/beta/gux-time-picker/tests/gux-time-picker.e2e.ts, src/components/beta/gux-time-picker/tests/gux-time-picker.spec.ts
=> feat(time-picker): enabled shadow dom

.github/workflows/main.yml, CONTRIBUTING.md, Jenkinsfile, playground/ember-3/.travis.yml
prepare for master branch rename to main
COMUI-900
=> feat(branch-name): prepare for master branch rename to main

playground/vue-2/src/components/HelloWorld.vue
=> docs(vue-2): updated example to show fix to COMUI-685

docs/src/component-viewer/app.js
fixed call to axe-live in docs
COMUI-957
=> fix(axe-live): fixed call to axe-live in docs

src/components/stable/gux-form-field/gux-form-field.tsx
explicitly set shadowDOM to false
COMUI-750
=> feat(form-field): explicitly set shadowDOM to false

CONTRIBUTING.md
added known issue with jest CLI argument
COMUI-959
=> docs(jest): added known issue with jest CLI argument

src/components/stable/gux-dropdown/gux-dropdown.tsx
Explicitly set shadowDOM to false. Related to task COMUI-874.
=> feat(gux-dropdown): explicitly set shadowDOM to false

src/components/beta/gux-tag/example.html, src/components/beta/gux-tag/gux-tag.less, src/components/beta/gux-tag/gux-tag.types.ts, src/components/beta/gux-tag/readme.md, src/components/beta/gux-tag/tests/gux-tag.e2e.ts
Addition of 'subtle' styling to the gux-tag colour palette.
=> feat(gux-tag): addition of subtle styling

src/components/stable/gux-datepicker/gux-datepicker.tsx
toggle focus is now working
COMUI-943
=> fix(datepicker): toggle focus is now working

src/components/beta/gux-card/example.html, src/components/beta/gux-card/gux-card.less, src/components/beta/gux-card/gux-card.tsx, src/components/beta/gux-card/gux-card.types.ts, src/components/beta/gux-card/readme.md, src/components/beta/gux-card/tests/__snapshots__/gux-card.e2e.ts.snap, src/components/beta/gux-card/tests/__snapshots__/gux-card.spec.ts.snap, src/components/beta/gux-card/tests/gux-card.e2e.ts, src/components/beta/gux-card/tests/gux-card.spec.ts
=> feat(gux-card): addition of new card component

src/components/beta/gux-badge/example.html, src/components/beta/gux-badge/gux-badge.less, src/components/beta/gux-badge/gux-badge.tsx, src/components/beta/gux-badge/gux-badge.types.ts, src/components/beta/gux-badge/i18n/en.json, src/components/beta/gux-badge/readme.md, src/components/beta/gux-badge/tests/__snapshots__/gux-badge.e2e.ts.snap, src/components/beta/gux-badge/tests/__snapshots__/gux-badge.spec.ts.snap, src/components/beta/gux-badge/tests/gux-badge.e2e.ts, src/components/beta/gux-badge/tests/gux-badge.spec.ts, src/components/stable/gux-tooltip-title/readme.md
=> feat(gux-badge) Creation of badge component.

src/components/stable/gux-pagination/gux-pagination-buttons/gux-pagination-buttons.less, src/components/stable/gux-pagination/gux-pagination-buttons/gux-pagination-buttons.tsx, src/components/stable/gux-pagination/gux-pagination-buttons/tests/__snapshots__/gux-pagination-buttons.spec.ts.snap
fixed focus style of button list
COMUI-1031
=> fix(pagination): fixed focus style of button list

README.md
removed IE11 support info from readme
COMUI-1041
=> docs(readme): removed IE11 support info from readme

.gitignore, .npmrc, Docs.Jenkinsfile, Jenkinsfile, REACT_INTEGRATION.md, README.md, docs/.npmrc, docs/migrations/v3/readme.md, docs/package-lock.json, package-lock.json, package.json, stencil.config.ts
This sets us up for publishing to the public NPM registry, and updates the README to be more suitable for a public-facing project.
=> ci: Publish to public NPM repo

src/components/beta/gux-form-field-v2/components/gux-form-field-checkbox/gux-form-field-checkbox.less, src/components/beta/gux-form-field-v2/components/gux-form-field-checkbox/gux-form-field-checkbox.light.less, src/components/beta/gux-form-field-v2/components/gux-form-field-color/gux-form-field-color.less, src/components/beta/gux-form-field-v2/components/gux-form-field-number/gux-form-field-number.less, src/components/beta/gux-form-field-v2/components/gux-form-field-radio/gux-form-field-radio.less, src/components/beta/gux-form-field-v2/components/gux-form-field-radio/gux-form-field-radio.light.less, src/components/beta/gux-form-field-v2/components/gux-form-field-range/gux-form-field-range.light.less, src/components/beta/gux-form-field-v2/components/gux-form-field-search/gux-form-field-search.less, src/components/beta/gux-form-field-v2/components/gux-form-field-select/gux-form-field-select.less, src/components/beta/gux-form-field-v2/components/gux-form-field-text-like/gux-form-field-text-like.less, src/components/beta/gux-form-field-v2/components/gux-form-field-textarea/gux-form-field-textarea.less, src/style/mixins.less
=> fix(form-field): fixed focus states

src/components/stable/gux-form-field/components/gux-form-field-select/gux-form-field-select.less, src/components/stable/gux-form-field/functional-components/gux-form-field-label/gux-form-field-label.less
COMUI-1051 https://inindca.atlassian.net/browse/COMUI-1051
=> fix(gux-form-field): fix label alignment

src/components/beta/gux-chart-scatter-plot/example.html, src/components/beta/gux-chart-scatter-plot/gux-chart-scatter-plot.less, src/components/beta/gux-chart-scatter-plot/gux-chart-scatter-plot.tsx, src/components/beta/gux-chart-scatter-plot/readme.md, src/components/beta/gux-chart-scatter-plot/tests/gux-chart-scatter-plot.spec.ts
=> Feature/com UI 939 scatter plot

src/components/beta/gux-button-slot/gux-button-slot.less, src/components/stable/gux-button/gux-button.less
COMUI-1071
Updated the ghost button styling in gux-button and gux-button-slot
=> style(gux-button): update ghost button active and hover state colors

Jenkinsfile, React.Jenkinsfile
Make a new Jenkins job for the react wrapper
=> build(react-wrapper): jenkinsfile for react wrapper

src/components/beta/gux-table/example.html, src/components/beta/gux-table/gux-sort-control/gux-sort-control.less, src/components/beta/gux-table/gux-sort-control/gux-sort-control.tsx, src/components/beta/gux-table/gux-sort-control/readme.md, src/components/beta/gux-table/gux-table.light.less, src/components/beta/gux-table/gux-table.tsx, src/components/beta/gux-table/i18n/en.json, src/components/beta/gux-table/tests/gux-table.e2e.ts, src/components/stable/gux-icon/readme.md
initial skeleton code for th component.
=> feat(sort-control): sort control

src/components/beta/gux-tag/example.html, src/components/beta/gux-tag/gux-tag.less, src/components/beta/gux-tag/gux-tag.types.ts, src/components/beta/gux-tag/readme.md, src/components/beta/gux-tag/tests/gux-tag.e2e.ts, src/style/color-palette.less, src/style/css-custom-properties.less, src/style/examples/color.html
fixed typo of fuchsia without a breaking change
COMUI-1109
=> fix(typo): fixed typo of fuchsia

src/i18n/DateTimeFormatter.ts, src/index.js
[COMUI-1084](https://inindca.atlassian.net/browse/COMUI-1084)
Using the IntlAPI, implemented `formatDate`, `formatTime` and `formatDateTime` methods to format dates and times with the options `short`, `long` and `full`.
=> [COMUI-1084] Create I18n object to format dates and times

docs/migrations/v3/readme.md
added info on gux-search-beta
COMUI-1113
=> docs(v3-migration): added info on gux-search-beta

.github/workflows/main.yml
This updates the github actions to add a link to the demo docs for feature branches.
=> ci(github action): add demo URL comment on feature PRs

docs/migrations/v3/gux-list-legacy.md
added info on IListItem removal
COMUI-1093
=> fix(v3-migration): added info on IListItem removal

src/components/stable/gux-button-multi/example.html, src/components/stable/gux-button-multi/gux-button-multi.less, src/components/stable/gux-button-multi/gux-button-multi.light.less, src/components/stable/gux-button-multi/gux-button-multi.tsx, src/components/stable/gux-button-multi/readme.md, src/style/style.less
COMUI-1101
In the Spark documentation, the multi-button can include an icon with text and an icon only. Adding this functionality here.
=> feat(gux-button-multi): add icon option to multi button

src/components/stable/gux-form-field/components/gux-form-field-search/gux-form-field-search.less
change search icon to be 16px
COMUI-1175
https://inindca.atlassian.net/browse/COMUI-1175
=> style(form-field-search): change search icon to be 16px

src/style/color-palette.less
=> fix(color-palette): update Red 70 color to match Spark color system

src/components/beta/gux-dropdown-v2/gux-dropdown-v2.tsx
added missing if guard
COMUI-1176
=> fix(dropdown_v2): added missing if guard

playground/knockout-3/index.html, playground/knockout-3/package-lock.json, playground/knockout-3/package.json
added knockout playground
COMUI-1159
=> fix(knockout): added knockout playground

package.json, src/components/stable/gux-tooltip/gux-tooltip.less, stylelint.config.js
moved config to seperate file
COMUI-988
=> build(stylelint): moved config to seperate file

src/components/stable/gux-tooltip/gux-tooltip.less, src/components/stable/gux-tooltip/gux-tooltip.tsx, src/components/stable/gux-tooltip/tests/__snapshots__/gux-tooltip.spec.ts.snap
isolated tooltip styling
COMUI-1165
=> fix(tooltip): isolated tooltip styling

scripts/list-i18n-files.js
updated list-i18n-files script to give clearer output
COMUI-1142
=> fix(script): updated list-i18n-files script to give clearer output

src/components/beta/gux-announce/a11yManualChecklist.md, src/components/beta/gux-announce/example.html, src/components/beta/gux-announce/gux-announce.less, src/components/beta/gux-announce/gux-announce.tsx, src/components/beta/gux-announce/gux-announce.types.ts, src/components/beta/gux-announce/readme.md
=> feat(announce): added new component

src/components/stable/gux-form-field/components/gux-form-field-number/example.html, src/components/stable/gux-form-field/components/gux-form-field-number/gux-form-field-number.less, src/components/stable/gux-form-field/components/gux-form-field-number/gux-form-field-number.tsx, src/components/stable/gux-form-field/components/gux-form-field-number/readme.md, src/components/stable/gux-form-field/components/gux-form-field-number/tests/__snapshots__/gux-form-field-number.e2e.ts.snap, src/components/stable/gux-form-field/components/gux-form-field-number/tests/__snapshots__/gux-form-field-number.spec.ts.snap
add part to style input container width
COMUI-1186
=> feat(form-field): add part to style input container width

.husky/pre-commit, package.json, scripts/build-i18n.js, scripts/update-en-i18n.js, src/i18n/translations/ar.json, src/i18n/translations/cs.json, src/i18n/translations/da.json, src/i18n/translations/de.json, src/i18n/translations/en.json, src/i18n/translations/es-es.json, src/i18n/translations/es.json, src/i18n/translations/fi.json, src/i18n/translations/fr-ca.json, src/i18n/translations/fr.json, src/i18n/translations/he.json, src/i18n/translations/it.json, src/i18n/translations/ja.json, src/i18n/translations/ko.json, src/i18n/translations/nl.json, src/i18n/translations/no.json, src/i18n/translations/pl.json, src/i18n/translations/pt-br.json, src/i18n/translations/pt-pt.json, src/i18n/translations/ru.json, src/i18n/translations/sv.json, src/i18n/translations/th.json, src/i18n/translations/tr.json, src/i18n/translations/zh-cn.json, src/i18n/translations/zh-tw.json
moved translations out of component folders
COMUI-1064
=> feat(translations): moved translations out of component folders

src/components/stable/gux-toggle/gux-toggle.tsx
=> fix(toggle): fixed check event detail

src/components/beta/gux-button-slot/example.html, src/components/beta/gux-button-slot/gux-button-slot.less, src/components/beta/gux-button-slot/readme.md, src/components/beta/gux-button-slot/tests/__snapshots__/gux-button-slot.e2e.ts.snap, src/components/beta/gux-button-slot/tests/__snapshots__/gux-button-slot.spec.ts.snap, src/components/beta/gux-button-slot/tests/gux-button-slot.e2e.ts, src/components/beta/gux-button-slot/tests/gux-button-slot.spec.ts, src/components/legacy/gux-action-button-legacy/gux-action-button.tsx, src/components/legacy/gux-action-button-legacy/gux-button.types.ts, src/components/legacy/gux-action-button-legacy/readme.md, src/components/legacy/gux-button-multi-legacy/gux-button-multi.tsx, src/components/legacy/gux-button-multi-legacy/readme.md, src/components/stable/gux-action-button/example.html, src/components/stable/gux-action-button/gux-action-button.tsx, src/components/stable/gux-action-button/readme.md, src/components/stable/gux-button-multi/gux-button-multi.tsx, src/components/stable/gux-button-multi/readme.md, src/components/stable/gux-button/example.html, src/components/stable/gux-button/gux-button.less, src/components/stable/gux-button/gux-button.tsx, src/components/stable/gux-button/gux-button.types.ts, src/components/stable/gux-button/readme.md, src/components/stable/gux-button/tests/__snapshots__/gux-button.e2e.ts.snap, src/components/stable/gux-button/tests/__snapshots__/gux-button.spec.ts.snap, src/components/stable/gux-button/tests/gux-button.e2e.ts, src/components/stable/gux-button/tests/gux-button.spec.ts
**Related Task:** https://inindca.atlassian.net/browse/COMUI-1240
**Acceptance criteria**
- Add ‘danger’ accent to the gux-button component.
- Add the ‘danger’ variant to the gux-action-button
=> feat(button) - Addition of danger accent to gux-button, gux-action-button

.github/workflows/ux-review.yml
For now I'm just getting this PR up to demo and review the process with the UX team
=> ci(ux-review): add additional reviews, draft of process reminder

src/components/stable/gux-form-field/components/gux-form-field-search/example.html, src/components/stable/gux-form-field/components/gux-form-field-search/gux-form-field-search.tsx, src/components/stable/gux-form-field/components/gux-form-field-search/readme.md
Related Task: https://inindca.atlassian.net/browse/COMUI-1272
Addition of guxForceUpdate to `form-field-search`
=> fix(form-field-search): addition of guxForceUpdate to form-field-search

src/components/beta/gux-alert/example.html, src/components/beta/gux-alert/gux-inline-alert.less, src/components/beta/gux-alert/gux-inline-alert.tsx, src/components/beta/gux-alert/gux-inline-alert.types.ts, src/components/beta/gux-alert/i18n/en.json, src/components/beta/gux-alert/readme.md, src/components/beta/gux-alert/tests/__snapshots__/gux-inline-alert.e2e.ts.snap, src/components/beta/gux-alert/tests/__snapshots__/gux-inline-alert.spec.ts.snap, src/components/beta/gux-alert/tests/gux-inline-alert.e2e.ts, src/components/beta/gux-alert/tests/gux-inline-alert.spec.ts, src/components/stable/gux-icon/readme.md, src/components/stable/gux-tooltip-title/readme.md, src/i18n/translations/en.json
Related Task : https://inindca.atlassian.net/browse/COMUI-1153
Some things to note : 
- The icons and colors are fixed.
- There is no wrapping as alert language should be clear and brief.
- Open to changes on prop names etc.
=> feat(alert) - addition of alert component

src/components/beta/gux-dropdown-multi/example.html, src/components/beta/gux-dropdown-multi/gux-dropdown-multi.less, src/components/beta/gux-dropdown-multi/gux-dropdown-multi.tsx, src/components/beta/gux-dropdown-multi/readme.md, src/components/beta/gux-pagination-beta/gux-pagination-items-per-page-beta/readme.md, src/components/beta/gux-pagination-beta/readme.md, src/components/stable/gux-dropdown/example.html, src/components/stable/gux-dropdown/gux-dropdown.tsx, src/components/stable/gux-dropdown/readme.md, src/components/stable/gux-listbox-multi/gux-listbox-multi.less, src/components/stable/gux-listbox-multi/gux-listbox-multi.tsx, src/components/stable/gux-listbox-multi/i18n/en.json, src/components/stable/gux-listbox-multi/readme.md, src/components/stable/gux-listbox/gux-listbox.less, src/components/stable/gux-listbox/gux-listbox.tsx, src/components/stable/gux-listbox/i18n/en.json, src/components/stable/gux-listbox/readme.md, src/components/stable/gux-pagination/gux-pagination-items-per-page/readme.md, src/components/stable/gux-pagination/readme.md, src/components/stable/gux-radial-loading/readme.md, src/i18n/translations/en.json
=> feat(dropdown): added loading state

src/components/beta/gux-pagination-beta/gux-pagination-beta.less, src/components/beta/gux-pagination-beta/gux-pagination-beta.tsx, src/components/beta/gux-pagination-beta/gux-pagination-item-counts-beta/gux-pagination-item-counts-beta.less, src/components/beta/gux-pagination-beta/gux-pagination-items-per-page-beta/gux-pagination-items-per-page-beta.less, src/components/beta/gux-pagination-beta/tests/__snapshots__/gux-pagination-beta.spec.ts.snap
improved space dependent layout switching logic
COMUI-1298
=> fix(pagination-beta): improved space dependent layout switching logic

src/style/color-palette.less
updated color palette to latest colors
COMUI-1291
=> fix(color-palette): updated color palette to latest colors

src/components/stable/gux-form-field/components/gux-form-field-select/gux-form-field-select.less
See screen captures in https://inindca.atlassian.net/browse/COMUI-1319
=> fix(css): specify width of slotted <select> in gux-form-field-select

src/components/stable/gux-calendar/gux-calendar.less, src/components/stable/gux-calendar/gux-calendar.tsx
**Related Task** : https://inindca.atlassian.net/browse/COMUI-1099
Current month disabled date - Black-50 at 50% opacity
Outside current month disabled date - Black-100 at 50% opacity
Figma : https://www.figma.com/file/VSJnXWtxyb6WRmfd1XPJ4y/Date-Picker-Updates?node-id=7%3A1597
=> style(calendar) - update calendar disabled states

.lintstagedrc.json, commitlint.config.js, package.json, src/i18n/translations/da.json, src/i18n/translations/de.json, src/i18n/translations/he.json, src/i18n/translations/ja.json, src/i18n/translations/ko.json, src/i18n/translations/pt-br.json, src/i18n/translations/ru.json, src/i18n/translations/th.json, src/i18n/translations/tr.json
commitlint now only looks at relevant commits
COMUI-1320
=> fix(commitlint): commitlint now only looks at relevant commits

src/components/stable/gux-listbox/gux-listbox.service.ts
changed keypress search
COMUI-1318
=> fix(listbox): changed keypress search

src/components/stable/gux-datepicker/gux-datepicker.tsx, src/components/stable/gux-datepicker/tests/__snapshots__/gux-datepicker.spec.ts.snap
**Related Task** : https://inindca.atlassian.net/browse/COMUI-1342
@daragh-king-genesys your previous fix for advanced dropdown works well here too. I dont think there are any other components that have this issue.
=> fix(datepicker): addition of flip modifier to popper

src/components/stable/gux-calendar/gux-calendar.tsx, src/components/stable/gux-calendar/gux-calendar.types.ts, src/components/stable/gux-datepicker/gux-datepicker.tsx, src/i18n/index.ts
=> fix(calendar): improved startDayOfWeek type

src/components/stable/gux-calendar/readme.md, src/components/stable/gux-datepicker/readme.md, src/components/stable/gux-listbox/gux-listbox.tsx
enter on a fully filtered list does not select an item
COMUI-1359
=> fix(dropdown): enter on a fully filtered list does not select an item

.github/workflows/ux-review.yml
Updating the list of UX reviewers to reflect changes on the Spark team.
=> ci(ux-review): updating ux reviewer list

src/components/beta/gux-truncate/gux-truncate.tsx, src/components/beta/gux-truncate/readme.md, src/components/stable/gux-notification-toast/example.html, src/components/stable/gux-notification-toast/gux-notification-toast.less, src/components/stable/gux-notification-toast/gux-notification-toast.tsx, src/components/stable/gux-notification-toast/readme.md, src/components/stable/gux-notification-toast/tests/__snapshots__/gux-notification-toast.spec.ts.snap, src/components/stable/gux-simple-toast/example.html, src/components/stable/gux-simple-toast/gux-simple-toast.less, src/components/stable/gux-simple-toast/gux-simple-toast.tsx, src/components/stable/gux-simple-toast/readme.md, src/components/stable/gux-simple-toast/tests/__snapshots__/gux-simple-toast.spec.ts.snap, src/utils/dom/get-text-content-from-nodes.ts
fixed toast message overflow
COMUI-1360
=> fix(toast): fixed toast message overflow

src/components/beta/gux-time-picker/gux-time-picker.less
Add missing focus ring style to gux-time-picker-beta.
https://inindca.atlassian.net/browse/COMUI-1364
=> fix(time-picker): add focus ring

src/components/beta/gux-alert/gux-inline-alert.less, src/components/beta/gux-badge/gux-badge.less, src/components/stable/gux-tabs-advanced/gux-tab-advanced/gux-tab-advanced.less, src/components/stable/gux-tabs/gux-tab/gux-tab.less, src/components/stable/gux-tooltip-title/gux-tooltip-title.less
removed cursor styling
COMUI-1371
=> fix(tooltip-title): removed cursor styling

src/components/beta/gux-truncate/gux-truncate.tsx, src/components/stable/gux-tooltip-title/gux-tooltip-title.tsx
fixed angular update bug
COMUI-1375
=> fix(tooltip-title): fixed angular update bug

src/components/stable/gux-toggle/gux-toggle.less
https://inindca.atlassian.net/browse/GDS-1458
=> feat(gux-toggle): show pointer when hovering toggle component

src/components/beta/gux-truncate/gux-truncate.less
enabled pointer events
COMUI-1391
=> fix(truncate): enabled pointer events

src/components/stable/gux-form-field/functional-components/gux-form-field-error/gux-form-field-error.less
https://inindca.atlassian.net/browse/GDS-1463
=> fix(gux-form-field-error): match design for error message + icon

src/components/beta/gux-button-slot/readme.md, src/components/beta/gux-context-menu/example.html, src/components/beta/gux-context-menu/gux-context-menu.less, src/components/beta/gux-context-menu/gux-context-menu.tsx, src/components/beta/gux-context-menu/i18n/en.json, src/components/beta/gux-context-menu/readme.md, src/components/beta/gux-context-menu/tests/__snapshots__/gux-context-menu.spec.ts.snap, src/components/beta/gux-context-menu/tests/gux-context-menu.e2e.ts, src/components/beta/gux-context-menu/tests/gux-context-menu.spec.ts, src/components/stable/gux-icon/readme.md, src/components/stable/gux-list/gux-list.tsx, src/components/stable/gux-list/readme.md, src/components/stable/gux-popup/readme.md, src/i18n/translations/en.json, src/i18n/translations/fi.json
COMUI-1100
This is a draft PR to get initial feedback on proposed interface for the new component described in COMUI-1100.
=> feat(context-menu): add new webcomponent

src/components/stable/gux-tabs-advanced/gux-tab-advanced/gux-tab-advanced.tsx
fixed safari dropdown-option click bug
COMUI-1401
=> fix(advanced-tabs): fixed safari dropdown-option click bug

src/components/beta/gux-dropdown-multi/gux-dropdown-multi.less, src/components/stable/gux-dropdown/gux-dropdown.less
fixed style of filter text
COMUI-1402
=> fix(dropdown): fixed style of filter text

src/components/beta/gux-announce/readme.md, src/components/beta/gux-column-manager/example.html, src/components/beta/gux-column-manager/gux-column-manager-item/gux-column-manager-item.less, src/components/beta/gux-column-manager/gux-column-manager-item/gux-column-manager-item.service.tsx, src/components/beta/gux-column-manager/gux-column-manager-item/gux-column-manager-item.tsx, src/components/beta/gux-column-manager/gux-column-manager-item/i18n/en.json, src/components/beta/gux-column-manager/gux-column-manager-item/readme.md, src/components/beta/gux-column-manager/gux-column-manager-item/tests/gux-column-manager-item.service.spec.ts, src/components/beta/gux-column-manager/gux-column-manager.less, src/components/beta/gux-column-manager/gux-column-manager.service.tsx, src/components/beta/gux-column-manager/gux-column-manager.tsx, src/components/beta/gux-column-manager/gux-column-manager.type.ts, src/components/beta/gux-column-manager/gux-column-manager.types.ts, src/components/beta/gux-column-manager/i18n/en.json, src/components/beta/gux-column-manager/readme.md, src/components/stable/gux-content-search/gux-content-search.tsx, src/components/stable/gux-content-search/readme.md, src/components/stable/gux-form-field/components/gux-form-field-checkbox/readme.md, src/components/stable/gux-icon/readme.md, src/components/stable/gux-text-highlight/readme.md, src/i18n/index.ts, src/i18n/translations/en.json
added column manager component
COMUI-1221
=> feat(column-manager): added column manager component

src/components/beta/gux-announce/readme.md, src/components/beta/gux-phone-input/readme.md, src/components/stable/gux-toggle/example.html, src/components/stable/gux-toggle/gux-toggle-slider/gux-toggle-slider.tsx, src/components/stable/gux-toggle/gux-toggle.tsx, src/components/stable/gux-toggle/i18n/en.json, src/components/stable/gux-toggle/readme.md, src/components/stable/gux-toggle/tests/__snapshots__/gux-toggle.spec.ts.snap, src/i18n/translations/en.json
fixed some accessibility issues
COMUI-791
=> fix(toggle): fixed some accessibility issues

Jenkinsfile, scripts/stencil-wrapper.ts, stencil.config.ts
=> feat(stencil-wrapper): load assets from region domain

src/components/stable/gux-calendar/gux-calendar.less, src/components/stable/gux-datepicker/gux-datepicker.less
=> fix(calendar): removed shadow

documentation/COMPONENT_LOCALIZATION.md, documentation/CONTRIBUTING.md
updated localisation documentation
COMUI-1429
=> docs(localisation): updated localisation documentation

src/components/stable/gux-form-field/components/gux-form-field-color/gux-form-field-color.less
Updating the design of the color picker.
=> feat(gux-form-field-color): update design

package-lock.json
=> fix(lock-file): added missing reference

src/components/beta/gux-phone-input/example.html
added localised phone-input examples
COMUI-1456
=> refactor(phone-input-example): added localised phone-input examples

src/components/stable/gux-form-field/gux-form-field.service.ts, src/components/stable/gux-form-field/tests/gux-form-field.service.spec.ts
added guard to hasContent check
COMUI-1470
=> fix(form-field): added guard to hasContent check

src/components/beta/gux-dropdown-multi/gux-dropdown-multi.less, src/components/beta/gux-dropdown-multi/gux-dropdown-multi.tsx, src/components/stable/gux-dropdown/gux-dropdown.less, src/components/stable/gux-dropdown/gux-dropdown.tsx
now delegating focus as expected
COMUI-1469
=> fix(dropdown): now delegating focus as expected

src/components/beta/gux-time-picker/gux-time-picker.less, src/components/beta/gux-time-picker/gux-time-picker.tsx, src/components/beta/gux-time-picker/tests/__snapshots__/gux-time-picker.spec.ts.snap
fixed 12 hour picker alignment
COMUI-1467
=> fix(time-picker): fixed 12 hour picker alignment

src/components/stable/gux-simple-toast/gux-simple-toast.less
change icon size to 16x16
COMUI-1458
=> fix(simple-toast): change icon size to 16x16

.github/workflows/ux-review.yml
Removing Joy & Niamh who have left the team & adding Matt Gaughran who has joined us temporarily.
=> ci(ux-review): update ux reviewer list

src/components/beta/gux-dropdown-multi/gux-dropdown-multi.tsx
**Related Ticket**
https://inindca.atlassian.net/browse/COMUI-1380
**Description** 
Addition of MutationObserver to cover for case where listbox-multi is inserted at a later time.
If this change is approved, this will also need to implemented into the `gux-dropdown` component.
[COMUI-1380]: https://inindca.atlassian.net/browse/COMUI-1380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(dropdown-multi): addition of mutation observer to dropdown-multi

src/components/beta/gux-popover-beta/example.html, src/components/beta/gux-popover-beta/gux-popover-beta.less, src/components/beta/gux-popover-beta/gux-popover-beta.tsx, src/components/beta/gux-popover-beta/readme.md, src/components/beta/gux-popover-beta/tests/__snapshots__/gux-popover-beta.spec.ts.snap, src/components/beta/gux-popover-beta/tests/gux-popover-beta.e2e.ts, src/components/beta/gux-popover-beta/tests/gux-popover-beta.spec.ts, src/components/stable/gux-popover/tests/__snapshots__/gux-popover.spec.ts.snap, src/components/stable/gux-popover/tests/gux-popover.e2e.ts, src/components/stable/gux-popover/tests/gux-popover.spec.ts
**Related Ticket:** https://inindca.atlassian.net/browse/COMUI-1488
Implement new popover design into `gux-popover-beta` component.
Design: https://www.figma.com/file/vQxcSpzB12t4a47IOb6Gua/Spark---Component-Library?node-id=11545%3A178001&t=wsPaHxxGm1IPyXGj-0
This design has recently been implemented into `gux-popover` and you can view the merged PR here : https://github.com/MyPureCloud/genesys-webcomponents/pull/996
=> feat(popover-beta): implement new design to popover-beta

src/components/stable/gux-action-toast/example.html, src/components/stable/gux-notification-toast/example.html, src/components/stable/gux-simple-toast/example.html
Update `gux-toast` examples to have `aria-live` attribute.
Recently closed PR : 
https://github.com/MyPureCloud/genesys-webcomponents/pull/1114
=> perf(toast): update toast examples to include aria-live

src/components/beta/gux-popover-beta/gux-popover-beta.less, src/components/beta/gux-popover-list-beta/gux-popover-list-beta.less, src/components/stable/gux-tooltip/gux-tooltip.less
hiding now done with display not visibility
COMUI-1502
=> fix(popover-beta): hiding now done with display not visibility

src/components/stable/gux-tooltip/gux-tooltip.tsx
added connected check to logging
COMUI-1159
=> fix(tooltip): added connected check to logging

src/components/stable/gux-breadcrumbs/example.html, src/components/stable/gux-breadcrumbs/gux-breadcrumbs.tsx
changes to the slot now updates all children
COMUI-1541
=> fix(breadcrumb): changes to the slot now updates all children

src/components/stable/gux-dismiss-button/gux-dismiss-button.less, src/components/stable/gux-simple-toast/gux-simple-toast.less, src/components/stable/gux-simple-toast/gux-simple-toast.tsx, src/components/stable/gux-simple-toast/tests/__snapshots__/gux-simple-toast.spec.ts.snap
fixed dismiss button alignment
COMUI-1485
=> fix(simple-toast): fixed dismiss button alignment

src/components/beta/gux-alert/example.html, src/components/beta/gux-alert/gux-inline-alert.less
removed component max-width
COMUI-1524
=> fix(alert): removed component max-width

src/components/beta/gux-popover-beta/gux-popover-beta.less, src/components/stable/gux-popover/gux-popover.less
remove styling of slotted components
COMUI-1543
=> fix(popover): remove styling of slotted components

src/components/beta/gux-table-toolbar/gux-table-toolbar-action/gux-table-toolbar-action.tsx, src/components/beta/gux-table-toolbar/gux-table-toolbar-action/readme.md, src/components/beta/gux-table-toolbar/gux-table-toolbar-action/tests/__snapshots__/gux-table-toolbar-action.e2e.ts.snap, src/components/beta/gux-table-toolbar/gux-table-toolbar-action/tests/__snapshots__/gux-table-toolbar-action.spec.ts.snap, src/components/beta/gux-table-toolbar/gux-table-toolbar-action/tests/gux-table-toolbar-action.e2e.ts, src/components/beta/gux-table-toolbar/gux-table-toolbar-action/tests/gux-table-toolbar-action.spec.ts, src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/gux-table-toolbar-custom-action.tsx, src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/readme.md, src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/tests/__snapshots__/gux-table-toolbar-custom-action.e2e.ts.snap, src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/tests/__snapshots__/gux-table-toolbar-custom-action.spec.ts.snap, src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/tests/gux-table-toolbar-custom-action.e2e.ts, src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/tests/gux-table-toolbar-custom-action.spec.ts
**Related Ticket:**  https://inindca.atlassian.net/browse/COMUI-1517
Addition of `disabled` prop to `gux-table-toolbar-action` and `gux-table-toolbar-custom-action`.
=> feat(table-toolbar): addition of disabled prop

src/components/stable/gux-dropdown/gux-dropdown.less
fix filterable dropdown where text is invisible
COMUI-1583
https://inindca.atlassian.net/browse/COMUI-1583
=> fix(dropdown): fix filterable dropdown where text is invisible

Jenkinsfile
fixing branch tagging
COMUI-1589
=> fix(jenkins): fixing branch tagging

web-apps/genesys-spark-examples/scripts/generate-manifest.js
fix examples manifest bug
COMUI-1590
=> fix(jenkins): fix examples manifest bug

packages/genesys-spark-components/src/utils/decorator/on-click-outside.ts
addition of isConnected condition to if guard to ensure node is connected before initialisation
[COMUI-1582](https://inindca.atlassian.net/browse/COMUI-1582)
[COMUI-1582]: https://inindca.atlassian.net/browse/COMUI-1582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(on-click-outside): addition of isConnected condition to if guard

packages/genesys-spark-components/src/components/beta/gux-button-slot/example.html, packages/genesys-spark-components/src/components/beta/gux-button-slot/gux-button-slot.less, packages/genesys-spark-components/src/components/beta/gux-button-slot/readme.md, packages/genesys-spark-components/src/components/beta/gux-button-slot/tests/__snapshots__/gux-button-slot.e2e.ts.snap, packages/genesys-spark-components/src/components/beta/gux-button-slot/tests/__snapshots__/gux-button-slot.spec.ts.snap, packages/genesys-spark-components/src/components/beta/gux-button-slot/tests/gux-button-slot.e2e.ts, packages/genesys-spark-components/src/components/beta/gux-button-slot/tests/gux-button-slot.spec.ts, packages/genesys-spark-components/src/components/stable/gux-action-button/example.html, packages/genesys-spark-components/src/components/stable/gux-action-button/gux-action-button.tsx, packages/genesys-spark-components/src/components/stable/gux-action-button/gux-action-button.types.ts, packages/genesys-spark-components/src/components/stable/gux-action-button/readme.md, packages/genesys-spark-components/src/components/stable/gux-button-multi/example.html, packages/genesys-spark-components/src/components/stable/gux-button-multi/gux-button-multi.tsx, packages/genesys-spark-components/src/components/stable/gux-button-multi/gux-button-multi.types.ts, packages/genesys-spark-components/src/components/stable/gux-button-multi/readme.md, packages/genesys-spark-components/src/components/stable/gux-button/example.html, packages/genesys-spark-components/src/components/stable/gux-button/gux-button.less, packages/genesys-spark-components/src/components/stable/gux-button/gux-button.types.ts, packages/genesys-spark-components/src/components/stable/gux-button/readme.md, packages/genesys-spark-components/src/components/stable/gux-button/tests/__snapshots__/gux-button.e2e.ts.snap, packages/genesys-spark-components/src/components/stable/gux-button/tests/__snapshots__/gux-button.spec.ts.snap, packages/genesys-spark-components/src/components/stable/gux-button/tests/gux-button.e2e.ts, packages/genesys-spark-components/src/components/stable/gux-button/tests/gux-button.spec.ts
added inline button style
COMUI-1574
=> feat(inline-button): added inline button style

packages/genesys-spark-components/src/components/beta/gux-copy-to-clipboard/gux-copy-to-clipboard.tsx, packages/genesys-spark-components/src/components/beta/gux-copy-to-clipboard/i18n/en.json, packages/genesys-spark-components/src/components/beta/gux-copy-to-clipboard/tests/__snapshots__/gux-copy-to-clipboard.spec.ts.snap, packages/genesys-spark-components/src/i18n/translations/en.json
removed unnecessary button title attribute
COMUI-1617
=> fix(copy-to-clipboard): removed unnecessary button title attribute

packages/genesys-spark-components/src/components/beta/gux-card/example.html, packages/genesys-spark-components/src/components/beta/gux-card/gux-card.less, packages/genesys-spark-components/src/components/beta/gux-card/gux-card.tsx, packages/genesys-spark-components/src/components/beta/gux-card/tests/__snapshots__/gux-card.spec.ts.snap
moved accent styles into the shadow dom
COMUI-1609
=> fix(card): moved accent styles into the shadow dom

README.md, package-lock.json, package.json, packages/genesys-spark-components-react/package.json, packages/genesys-spark-components/package.json, packages/genesys-spark-components/src/components/beta/gux-truncate/gux-truncate.less, web-apps/genesys-spark-examples/package.json
changed layout to block
COMUI-1600
=> fix(truncate): changed layout to block

packages/genesys-spark-components/src/components/beta/gux-pagination-beta/gux-pagination-items-per-page-beta/gux-pagination-items-per-page-beta.tsx, packages/genesys-spark-components/src/components/beta/gux-pagination-beta/gux-pagination-items-per-page-beta/i18n/en.json, packages/genesys-spark-components/src/components/beta/gux-pagination-beta/gux-pagination-items-per-page-beta/tests/__snapshots__/gux-pagination-items-per-page-beta.spec.ts.snap, packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-items-per-page/gux-pagination-items-per-page.tsx, packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-items-per-page/i18n/en.json, packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-items-per-page/tests/__snapshots__/gux-pagination-items-per-page.spec.ts.snap, packages/genesys-spark-components/src/components/stable/gux-pagination/tests/__snapshots__/gux-pagination.spec.ts.snap, packages/genesys-spark-components/src/i18n/translations/en.json
https://inindca.atlassian.net/browse/COMUI-1604
=> perf(pagination) - update screenreader-text for items-per-page dropdown

Jenkinsfile, package-lock.json, packages/genesys-spark-components/package.json
added tokens dev dependency to components
COMUI-1587
=> feat(tokens): added tokens dev dependency to components

packages/genesys-spark-components/src/components/beta/gux-card/gux-card.less
fixed card width styling
COMUI-1631
=> fix(card): fixed card width styling

.github/workflows/main.yml, Jenkinsfile, package.json, packages/genesys-spark-components/src/components/beta/gux-copy-to-clipboard/gux-copy-to-clipboard.tsx
stopped keyboard focus messaging on mouse focus
COMUI-1620
=> fix(copy-to-clipboard): stopped keyboard focus messaging on mouse focus

Jenkinsfile, package-lock.json, packages/genesys-spark-components-react/package.json
saving exact components dependency during release
COMUI-1633
=> fix(react): saving exact components dependency during release

Jenkinsfile
=> fix(jenkins): fix version sync

packages/genesys-spark-components/src/components/beta/gux-card/example.html, packages/genesys-spark-components/src/components/beta/gux-card/gux-card.less
fixed slot containers display type.
COMUI-1645
=> fix(card): fixed slot containers display type

.gitignore, packages/genesys-spark-components/.gitignore
remove files added by Jenkins in error
=> build(files): remove files added by Jenkins in error

packages/genesys-spark-components/src/components/beta/gux-dropdown-multi/gux-dropdown-multi.less, packages/genesys-spark-components/src/components/beta/gux-popup-beta/gux-popup-beta.less, packages/genesys-spark-components/src/components/beta/gux-popup-beta/gux-popup-beta.tsx, packages/genesys-spark-components/src/components/beta/gux-popup-beta/readme.md, packages/genesys-spark-components/src/components/beta/gux-popup-beta/tests/__snapshots__/gux-popup-beta.spec.ts.snap, packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar-menu-button/gux-table-toolbar-menu-button.less, packages/genesys-spark-components/src/components/stable/gux-action-button/gux-action-button.less, packages/genesys-spark-components/src/components/stable/gux-advanced-dropdown/gux-advanced-dropdown.less, packages/genesys-spark-components/src/components/stable/gux-button-multi/gux-button-multi.less, packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.less
allow list to exceed width of button
[COMUI-1564](https://inindca.atlassian.net/browse/COMUI-1564)
[COMUI-1564]: https://inindca.atlassian.net/browse/COMUI-1564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(button): allow list to exceed width of button

packages/genesys-spark-components/src/components/stable/gux-popover/gux-popover.tsx
allow popover to search shadowRoot
Syncing logic with `gux-popover-beta`
COMUI-1540
=> perf(popover): allow popover to search shadowRoot

packages/genesys-spark-components/src/components/beta/gux-time-picker/gux-time-picker.service.tsx
arabic now uses 24h layout
COMUI-1696
=> fix(time-picker): arabic now uses 24h layout

packages/genesys-spark-components/src/components/stable/gux-tabs-advanced/gux-tab-advanced-list/gux-tab-advanced-list.tsx
Watch for dynamic changes to allowSort prop
[COMUI-1691](https://inindca.atlassian.net/browse/COMUI-1691)
[COMUI-1691]: https://inindca.atlassian.net/browse/COMUI-1691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(tab-advanced-list): watch for dynamic changes to allowSort prop

packages/genesys-spark-components/package.json, packages/genesys-spark-components/scripts/list-light-dom-components.js, packages/genesys-spark-components/src/components/beta/gux-month-picker/gux-month-calendar/gux-month-list/gux-month-list-item/gux-month-list-item.tsx, packages/genesys-spark-components/src/components/beta/gux-month-picker/gux-month-calendar/gux-month-list/gux-month-list.tsx, packages/genesys-spark-components/src/components/beta/gux-table/gux-sort-control/gux-sort-control.tsx, packages/genesys-spark-components/src/components/stable/gux-list/gux-list-item/gux-list-item.tsx, packages/genesys-spark-components/src/components/stable/gux-list/gux-list.tsx
=> chore(script): add script to list light dom components and subcomponents

web-apps/genesys-spark-examples/scripts/generate-versions-file.mjs
removed duplicates from generated version file
COMUI-1716
=> fix(versions-file): removed duplicates from generated version file

packages/genesys-spark-components/src/components/stable/gux-calendar/tests/gux-calendar.service.spec.ts
removed spurious failing test temporarily
COMUI-1738
=> fix(calendar): removed spurious failing test temporarily

.github/workflows/ux-review.yml
=> chore(github-action): fix formatting in UX review Github Action

packages/genesys-spark-components/src/style/style.less
import tokens from node_modules
COMUI-1740
=> fix(css): import tokens from node_modules

packages/genesys-spark-components/src/utils/decorator/on-mutation.ts, packages/genesys-spark-components/src/utils/decorator/on-resize.ts
unobserve single element instead of unobserving all elements when a `table-toolbar` instance is removed from the DOM to prevent break in responsive layout.
**Question**
Just to clarify would I be correct in saying only one `resize-observer` instance would be created if we had two `table-toolbars` in the DOM so there would be one `resize-observer` observing the two `table-toolbars`. 
Instead of using the `disconnect` method which would unobserve all elements instead just use `unobserve` method to unobserve the single element in question.
[COMUI-1709](https://inindca.atlassian.net/browse/COMUI-1709)
[COMUI-1709]: https://inindca.atlassian.net/browse/COMUI-1709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(table-toolbar): unobserve single element instead of unobserving all elements.

packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar-action/gux-table-toolbar-action.less, packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar-action/gux-table-toolbar-action.tsx, packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar-custom-action/gux-table-toolbar-custom-action.less
add pointer events none to disabled elements
[COMUI-1741](https://inindca.atlassian.net/browse/COMUI-1741)
[COMUI-1741]: https://inindca.atlassian.net/browse/COMUI-1741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(table-toolbar): add pointer events none to disabled elements.

README.md
update readme links
COMUI-1732
=> docs(readme): update documentation links

packages/genesys-spark-components/src/utils/dom/find-element-by-id.ts
It needs to check if it is a Document.Fragment.Node.
COMUI-2000
=> fix(util): fix findElementById util bug

packages/genesys-spark-components/src/components/beta/gux-error-message-beta/readme.md, packages/genesys-spark-components/src/components/stable/gux-icon/readme.md, packages/genesys-spark-components/src/components/stable/gux-toggle/gux-toggle.less, packages/genesys-spark-components/src/components/stable/gux-toggle/gux-toggle.tsx, packages/genesys-spark-components/src/components/stable/gux-toggle/readme.md
removing dependency on gux-error-message-beta component
COMUI-1851
=> fix(toggle): removing dependency on gux-error-message-beta component

packages/genesys-spark-components/src/components/stable/gux-tooltip-title/gux-tooltip-title.scss, packages/genesys-spark-components/src/components/stable/gux-tooltip-title/gux-tooltip-title.tsx, packages/genesys-spark-components/src/style/spacing.scss, packages/genesys-spark-components/src/style/variables.scss
[COMUI-2092](https://inindca.atlassian.net/browse/COMUI-2092)
[COMUI-2092]: https://inindca.atlassian.net/browse/COMUI-2092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(tooltip-title): converting less files to scss

packages/genesys-spark-components/documentation/migrations/v4/readme.md
started V4 migration guide
COMUI-1911
=> docs(migration-guide): started V4 migration guide

.github/workflows/add-reviewers.yml
add review lottery to the beta branch
=> ci(github-actions): add review lottery to the beta branch

package.json, packages/genesys-spark-components/package.json, packages/genesys-spark-components/scripts/check-a11y.mjs
=> fix(a11y): fixed check-a11y script

packages/genesys-spark-components/src/components/beta/gux-copy-to-clipboard/tests/gux-copy-to-clipboard.spec.ts
removed unused reference to popperjs
COMUI-2140
=> refactor(copy-to-clipboard): removed unused reference to popperjs

packages/genesys-spark-components/src/components/stable/gux-alert/example.html, packages/genesys-spark-components/src/components/stable/gux-alert/gux-inline-alert.scss, packages/genesys-spark-components/src/components/stable/gux-alert/gux-inline-alert.tsx, packages/genesys-spark-components/src/components/stable/gux-alert/readme.md
https://inindca.atlassian.net/browse/COMUI-1684
=> refactor(inline-alert) - component reskin

packages/genesys-spark-components/src/components/stable/gux-icon/readme.md
=> chore(build): fixed icon readme file

package.json
Fixed broken build from an incorrect commit message structure.
=> fix(commitlint): fixed broken build

packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-listbox-multi.tsx, packages/genesys-spark-components/src/components/stable/gux-listbox/gux-listbox.tsx
made empty message configurable
COMUI-2133
=> feat(listbox): made empty message configurable

package-lock.json, package.json, packages/genesys-spark-components-react/package.json, packages/genesys-spark-components/CHANGELOG.md, packages/genesys-spark-components/package.json, web-apps/genesys-spark-examples/package.json
Trying to fix the prerelease beta branch. The publish step [worked as expected](https://www.npmjs.com/package/genesys-spark-components/v/4.0.0-beta.0), but the version bump did not work as expected. I manually bumped the version, so hopefully this will get [the broken build](https://jenkins.ininica.com/view/Common%20UI/job/cui-web-component-feature-multi/job/beta%252Fv4/) back to normal
=> chore(release): 4.0.0-beta.0

packages/genesys-spark-components/documentation/migrations/v4/readme.md
Open to changes to the descriptions.
COMUI-1974
=> docs(migration) - update tooltip migration guide.

packages/genesys-spark-components/src/components/stable/gux-alert/gux-inline-alert.scss, packages/genesys-spark-components/src/components/stable/gux-alert/readme.md
Addition of missing tokens.
https://inindca.atlassian.net/browse/COMUI-2134
=> style(inline-alert): adding missing tokens

packages/genesys-spark-components/src/components/stable/gux-rating/gux-rating.scss, packages/genesys-spark-components/src/components/stable/gux-rating/gux-rating.tsx, packages/genesys-spark-components/src/components/stable/gux-rating/readme.md
=> refactor(rating): component reskin

packages/genesys-spark-components/src/components/stable/gux-icon/gux-icon.tsx
(cherry picked from commit 22f3567442f5c882ba075573fe88e7174757f52a)
=> fix(gux-icon): prevent updates to svgHtml if baseSvgHtml is not set

packages/genesys-spark-components/src/components/stable/gux-popup/gux-popup.scss, packages/genesys-spark-components/src/components/stable/gux-popup/gux-popup.tsx
hide popup when target element goes out of view
COMUI-2198
=> feat(gux-popup-beta): hide popup when target element goes out of view

package-lock.json, package.json, packages/genesys-spark-components-react/package.json, packages/genesys-spark-components/CHANGELOG.md, packages/genesys-spark-components/package.json, web-apps/genesys-spark-examples/package.json
bump version to fix Jenkins build
=> chore(release): 4.0.0-beta.11

packages/genesys-spark-components/documentation/migrations/v4/readme.md, packages/genesys-spark-components/src/components/stable/gux-form-field/functional-components/gux-form-field-container/gux-form-field-container.less
Removed hardcoded margin in form field components. There will be follow up wrapper form field components that will define their own margin.
=> refactor(form field margin): Remove hardcoded margin in form field components

packages/genesys-spark-components/documentation/migrations/v4/readme.md, packages/genesys-spark-components/src/components/beta/gux-column-manager/gux-column-manager-item/gux-column-manager-item.less, packages/genesys-spark-components/src/components/beta/gux-column-manager/gux-column-manager-item/gux-column-manager-item.tsx, packages/genesys-spark-components/src/components/stable/gux-text-highlight/example.html, packages/genesys-spark-components/src/components/stable/gux-text-highlight/gux-text-highlight.scss, packages/genesys-spark-components/src/components/stable/gux-text-highlight/gux-text-highlight.tsx, packages/genesys-spark-components/src/components/stable/gux-text-highlight/readme.md, packages/genesys-spark-components/src/style/style.less
added dimmed property
COMUI-2105
=> feat(text-highlight): added dimmed property

packages/genesys-spark-components/documentation/migrations/v4/readme.md, packages/genesys-spark-components/src/components/stable/gux-popover/gux-popover.less
apply a min-width of 280px
COMUI-1487
https://inindca.atlassian.net/browse/COMUI-1487
=> refactor(popover): apply a min-width of 280px
